// 由 design/export_swift.py 生成，不要手改。
// 想改宠物：改 design/ 里的 Python 原型，python3 design/pet_pixel.py 出预览图，满意了再运行 python3 design/export_swift.py。

/// 宠物的像素数据：每款形象一张不带五官的底图，加上可以叠上去的眼睛、嘴、小道具。
public enum PetArt {
    struct Patch: Sendable {
        let x: Int
        let y: Int
        let rows: [String]
    }

    struct Layers: Sendable {
        let base: [String]
        let eyes: [String: Patch]
        let mouths: [String: Patch]
        let extras: [String: Patch]
    }

    /// 一款形象：菜单栏头像 32×32（显示成 16pt）+ 面板半身像 64×64
    struct Look: Sendable {
        let icon: Layers
        let portrait: Layers
    }

    /// 调色板（各款共用）：字符 → 0xRRGGBB
    public static let palette: [Character: UInt32] = [
        "!": 0x948EBE,
        "#": 0x682C96,
        "$": 0x402460,
        "&": 0x9670C4,
        "'": 0x968ECC,
        "(": 0xFFFFFF,
        ")": 0x463E7C,
        "*": 0x3E1660,
        "+": 0x4E3A6E,
        ",": 0x7872AA,
        "-": 0x281A3E,
        "/": 0x4E487C,
        "0": 0x583084,
        "1": 0x925AC8,
        "2": 0xCCA0F0,
        "3": 0x28143C,
        "4": 0xE4DEEE,
        "5": 0x463658,
        "6": 0x584078,
        "7": 0xBEB4D2,
        "9": 0xFCFAFF,
        ":": 0x8882BC,
        ";": 0xC4C2EE,
        "<": 0x282446,
        "=": 0xCEC8F0,
        ">": 0xFAF8FF,
        "?": 0xE6E4F4,
        "@": 0x423C64,
        "A": 0x7A3510,
        "B": 0xC8661E,
        "C": 0xF5A93B,
        "D": 0xFFE26E,
        "E": 0x3A1A0A,
        "F": 0xF08A3C,
        "G": 0xE7B04A,
        "H": 0xE8743B,
        "I": 0x3A1C00,
        "J": 0x5C3A84,
        "K": 0x4A2A20,
        "L": 0x261636,
        "M": 0x8A3A2A,
        "N": 0x2B2222,
        "O": 0xE0662A,
        "P": 0xF7A08C,
        "Q": 0xFFF6EA,
        "R": 0x1E162E,
        "S": 0xFFE9DB,
        "T": 0xF07F7F,
        "U": 0xF2A43C,
        "V": 0x3E2C5C,
        "W": 0xFFFFFF,
        "X": 0x7CC8F8,
        "Y": 0xFFD34A,
        "Z": 0x8E9AAF,
        "[": 0xD4D2EA,
        "^": 0x38325C,
        "_": 0xA49CD2,
        "`": 0xFCFCFF,
        "b": 0x7A3E28,
        "c": 0x1A5C54,
        "d": 0xC4531F,
        "f": 0xC8561E,
        "g": 0x2E9680,
        "h": 0xF8AA70,
        "i": 0x82D6B4,
        "j": 0x0E3028,
        "k": 0x4E261A,
        "l": 0xBA7648,
        "m": 0xE84054,
        "o": 0x3A64B4,
        "p": 0xFAFCFF,
        "q": 0xEAD9C4,
        "r": 0x925630,
        "s": 0xF6CDB8,
        "u": 0xE8AC76,
        "v": 0xFC828C,
        "x": 0xC4D4EA,
        "y": 0x824E08,
        "z": 0xDEA01C,
        "|": 0x685EA4,
        "~": 0xBCB8DC,
    ]

    /// 经典
    static let classic = Look(
        icon: Layers(
            base: [
                "..............KKHHK.............",
                "..........KKKKHHHHKKKK..........",
                ".........KHHHHHHHHHHHHK.KKK.....",
                ".......KKHHHHHHhhhHHHHKKKKKK....",
                "......KHHHHhhhhHHHhhhKKKFFKKK...",
                ".....KHHHHhhHHHHHHHHHKKFGGfKK...",
                "....KHHHHhHHHHHHHHHHHKKFGGfKK...",
                "....KHHHhHHHHHHHHHHHHKKKffKKKKK.",
                "...KHHHHHHHHHHHHHHHHHHKKKKKKKNNK",
                "...KHHHHHHHHHHHHHHHHHHHKKKKKNNK.",
                "...KHHHHHHHHHHHHHHHHHHHHHNHNNNK.",
                "..KHHHHHHHHHHHHHHHHHHHHHHNHNNK..",
                "..KHHHHHHHsHHsHHHHHHsHHHHNHHNK..",
                "..KHHHHHHHSHHSHHssHsSsHsHNNHNNK.",
                "...KHHHHssSssSsHSSsSSSsSHHHHNNK.",
                "...KHHHHSSSSSSSsSSSSSSSSHHHHKK..",
                "..KHHHHHSSSSSSSSSSSSSSSSHHHHHK..",
                "..KHHHHHSSSSSSSSSSSSSSSSHHHHHK..",
                "..KHHHHHSSSSSSSSSSSSSSSSHHHHHK..",
                "..KHHHHHSSSSSSSSSSSSSSSSHHHHHK..",
                "..KHHHHHKSSSSSSSSSSSSSSSHHHHHK..",
                "..KHHHHHKPPPSSSSSSSSPPPKHHHHHK..",
                "..KHHHHHKKSSSSSSSSSSSSKKHHHHHK..",
                "..KHHHHHKdKSSSSSSSSSSKdKHHHHHK..",
                ".KHHHHHHKddKSSSSSSSSKddKHHHHHHK.",
                ".KHHHHHHKdddKSSSSSSKdddKHHHHHHK.",
                ".KHHHHHHKdddddKKKKdddddKHHHHHHK.",
                ".KHHHHHHKdddQQQQQQQQddddHHHHHHK.",
                ".KHHHHHHQqQQQQQQQQQQQQqQHHHHHHK.",
                ".KHHHHHqqQQQNNNGGNNNQQQqqQHHHHK.",
                ".KHHHQqQQQQQQNNQQNNQQQQQQqQHHHK.",
                ".KHHHqQQQQQQQQQQQQQQQQQQQQqQHHK.",
            ],
            eyes: [
                "open": Patch(x: 10, y: 16, rows: [".KKK....KKK.", "KWAA....AWAK", "AWEA....AWEA", "BEEB....BEEB", ".CC......CC."]),
                "sparkle": Patch(x: 10, y: 16, rows: [".KKK....KKK.", "KWAA....AWAK", "WWWA....WWWA", "BWEB....BWEB", ".CC......CC."]),
                "tired": Patch(x: 10, y: 17, rows: ["KKKK....KKKK", "AWEA....AWEA", "BEEB....BEEB", ".CC......CC."]),
                "cry": Patch(x: 10, y: 17, rows: ["KK........KK", "..KK....KK..", "KK........KK"]),
                "closed": Patch(x: 10, y: 18, rows: ["K..K....K..K", ".KK......KK."]),
                "happy": Patch(x: 10, y: 17, rows: [".KK......KK.", "K..K....K..K"]),
            ],
            mouths: [
                "open": Patch(x: 15, y: 22, rows: ["MM", "MM"]),
                "wavy": Patch(x: 15, y: 23, rows: ["MM"]),
                "o": Patch(x: 15, y: 23, rows: ["MM"]),
            ],
            extras: [
                "starBig": Patch(x: 1, y: 2, rows: [".Y.", "YYY", ".Y."]),
                "starSmall": Patch(x: 2, y: 3, rows: ["Y"]),
                "sweatA": Patch(x: 3, y: 11, rows: [".X", "XX", "XX"]),
                "sweatB": Patch(x: 3, y: 12, rows: [".X", "XX", "XX"]),
                "tearsA": Patch(x: 10, y: 20, rows: ["X..........X", "X..........X"]),
                "tearsB": Patch(x: 10, y: 21, rows: ["X..........X", "X..........X"]),
                "zzzA": Patch(x: 0, y: 2, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "zzzB": Patch(x: 1, y: 0, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "question": Patch(x: 1, y: 1, rows: ["ZZ.", "..Z", ".Z.", "...", ".Z."]),
            ]
        ),
        portrait: Layers(
            base: [
                "................................................................",
                "................................KK..............................",
                "...............................KHHK.............................",
                "..........................KKKKKHHKKKKK..........................",
                ".......................KKKHHHHHHHHHHHHKKK.......................",
                ".....................KKHHHHHHHHHHHHHHHHHHKK..KKKK...............",
                "....................KHHHHHHHHHHHHHHHHHHHHHHKKKKKKKK.............",
                "...................KHHHHHHHHhhhhhhhhHHHHHHKKKKKKFKKK............",
                "..................KHHHHHHhhhhhhHHhhhhhhHHKKKKFKFFKKK............",
                ".................KHHHHhhhhHHHHHHHHHHHHhhhKKKKfffFKKKK...........",
                "................KHHHHHhhHHHHHHHHHHHHHHHHKKKFFGGGfFKKK...........",
                "...............KHHHHHhhHHHHHHHHHHHHHHHHHKKKKfGGGfFKKK...........",
                "..............KHHHHHhhHHHHHHHHHHHHHHHHHHKKKFFGGGfFKKK.K.........",
                ".............KHHHHHhhHHHHHHHHHHHHHHHHHHHKKKKKfffFKKKKKNK........",
                ".............KHHHHHHHHHHHHHHHHHHHHHHHHHHHKKKKFKFFKKKNNNK........",
                "............KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHKKKKKKFKKKNNNK........",
                "............KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHKKKKKKKKNNNNK........",
                "............KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHKKKKKNHNNNNK........",
                "...........KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHNHHNHNNNK........",
                "...........KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHNHHNHKNNK........",
                "...........KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHNHHNNKKK.........",
                "...........KHHHHHHHHHHssHHHHsHHHHsHHHHsHHHHsHHHNNHHNNK..........",
                "...........KHHHHHHHHHHSsHHHsSHHHHSsHHHSsHHHSHHHNNHHNNNK.........",
                "...........KHHHHHHHHsHSSsHHSSsHHsSSHHsSSsHsSHHHNNHHHNNK.........",
                "...........KHHHHHHHHSsSSSssSSSHHSSSssSSSSsSSHHHHHHHHNNK.........",
                "...........KHHHHHHHHSSSSSSSSSSsHSSSSSSSSSSSSHHHHHHHHKK..........",
                "...........KHHHHHHHHSSSSSSSSSSSsSSSSSSSSSSSSHHHHHHHHK...........",
                "...........KHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHK...........",
                "...........KHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHK...........",
                "...........KHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHK...........",
                "..........KHHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHHK..........",
                "..........KHHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHHK..........",
                "..........KHHHHHHHHsSSSSSSSSSSSSSSSSSSSSSSSSsHHHHHHHHK..........",
                "..........KHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHK..........",
                "..........KHHHHHHHHKSSSSSSSSSSSSSSSSSSSSSSSSKHHHHHHHHK..........",
                "..........KHHHHHHHHHKPPPPPSSSSSSSSSSSSPPPPPKHHHHHHHHHK..........",
                "..........KHHHHHHHHKKSPPPSSSSSSSSSSSSSSPPPSKKHHHHHHHHK..........",
                "..........KHHHHHHHHK.KSSSSSSSSSSSSSSSSSSSSK.KHHHHHHHHK..........",
                "..........KHHHHHHHHKKdKSSSSSSSSSSSSSSSSSSKdKKHHHHHHHHK..........",
                "..........KHHHHHHHHKKdKSSSSSSSSSSSSSSSSSKKdKKHHHHHHHHK..........",
                ".........KHHHHHHHHHKKddKKSSSSSSSSSSSSSSKKddKKHHHHHHHHHK.........",
                ".........KHHHHHHHHHKddddKKSSSSSSSSSSSSKKddddKHHHHHHHHHK.........",
                ".........KHHHHHHHHHKddddddKKSSSSSSSSKKddddddKHHHHHHHHHK.........",
                ".........KHHHHHHHHHKddddddddKKKKKKKKddddddddKHHHHHHHHHK.........",
                ".........KHHHHHHHHHKddddddddssssssssddddddddKHHHHHHHHHK.........",
                ".........KHHHHHHHHHKddddddQQQQQQQQQQQQddddddKHHHHHHHHHK.........",
                ".........KHHHHHHHHHQQQQQQQQQQQQQQQQQQQQQQQQQQHHHHHHHHHK.........",
                ".........KHHHHHHHHQQqqqQQQQQQQQFFQQQQQQQQqqqQQHHHHHHHHK.........",
                ".........KHHHHHHHQQqqQQQQQNNNNFffFNNNNQQQQQqqQQHHHHHHHK.........",
                ".........KHHHHHHQqqQQbbbbQQNNNFGGFNNNNQQQQQQQqqQHHHHHHK.........",
                ".........KHHHHHQbbbbbbbbbQQNNNQFFQNNNQQQQQQQQQqqQQHHHHK.........",
                ".........KHkbbbbbbbbbbbbbQQNQQQQQQQQNQQQQQQQQQQQqqQHHHK.........",
                ".........KHkbbbbbbbbbbbbbQQQQQQQQQQQQQQQQQQQQQQQOqQHHHK.........",
                "........KHHkkbbbbbbbbbbbbQQQQQQQQQQQQQQQQQQQQQQQOqQHHHHK........",
                "........KHHkkbbbbbbbbbbbbbSSQQQQQQQQQQQQQQQQQQQQqqQHHHHK........",
                "........KHHkkbbbbbbbbbbbbSSSSQQQQQQQQQQQQQQQQQQQqqQHHHHK........",
                "........KHHkkbbbbbbbbbbbbSSSSQQQQQQQQQQQQQQQQQOqqQQQHHHK........",
                "........KHHkkbbbbbFbFbbbbSSSSQQQQQQQQQQQQOqqqqQQQQQQHHHK........",
                "........KHHkkbbbbbFfFbbbSSSSQQQQQQQQQOqqqqQQQQQQQQQQHHHK........",
                "........KHHHkbbbbbfGGFbbSSSSqqqOOqqqqqQQQQQQQQQQQQQQHHHK........",
                "........KHHHkbbbbFfGfFbbbSSQQQQqqQQQQQQQQQQQQQQQQQQQQHHK........",
                "........KHHQkkbbbbFFFbbbbbbQQQQQQQQQQQQQQQQQQQQQQQQQQHHK........",
                "........KHHQkkbbbbbbbbbbbbbQQQQQQQQQQQQQQQQQQQQQQQQQQHHK........",
                "........KHHQkkbbbbbbbbbbbbbQQQQQQQQQQQQQQQQQQQQQQQQQQHHK........",
            ],
            eyes: [
                "open": Patch(x: 23, y: 27, rows: [".KKKK........KKKK.", "KKAAAK......KAAAKK", "AWWEAA......AWWEAA", "AWEEBA......AWEEBA", "BBEEBB......BBEEBB", ".BCCWB.......BCCWB", "..CC..........CC.."]),
                "sparkle": Patch(x: 23, y: 27, rows: [".KKKK........KKKK.", "KKWAAK......KAWAKK", "AWWWEA......AWWWEA", "AAWEEB......AAWEEB", "BBEEBB......BBEEBB", ".BCCWB.......BCCWB", "..CC..........CC.."]),
                "tired": Patch(x: 23, y: 29, rows: ["KKKKKK......KKKKKK", "AWEEBA......AWEEBA", "BBEEBB......BBEEBB", ".BCCWB.......BCCWB", "..CC..........CC.."]),
                "cry": Patch(x: 23, y: 28, rows: ["KK..............KK", "..KK..........KK..", "....KK......KK....", "..KK..........KK..", "KK..............KK"]),
                "closed": Patch(x: 23, y: 30, rows: ["K....K......K....K", ".KKKK........KKKK."]),
                "happy": Patch(x: 23, y: 29, rows: ["..KK..........KK..", ".K..K........K..K.", "K....K......K....K"]),
            ],
            mouths: [
                "small": Patch(x: 31, y: 38, rows: ["MM"]),
                "open": Patch(x: 30, y: 38, rows: ["MMMM", "MTTM", ".TT."]),
                "wavy": Patch(x: 30, y: 38, rows: ["MMMM"]),
                "o": Patch(x: 31, y: 38, rows: ["MM", "MM", "MM"]),
            ],
            extras: [
                "starBig": Patch(x: 3, y: 5, rows: ["..Y..", ".YYY.", "YYYYY", ".YYY.", "..Y.."]),
                "starSmall": Patch(x: 4, y: 6, rows: [".Y.", "YYY", ".Y."]),
                "sweatA": Patch(x: 8, y: 18, rows: [".X.", "XXX", "XXX", ".X."]),
                "sweatB": Patch(x: 8, y: 20, rows: [".X.", "XXX", "XXX", ".X."]),
                "tearsA": Patch(x: 25, y: 34, rows: ["X............X.", "XX...........XX", "XX...........XX"]),
                "tearsB": Patch(x: 25, y: 35, rows: ["X............X.", "XX...........XX", "XX...........XX"]),
                "zzzA": Patch(x: 3, y: 5, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "zzzB": Patch(x: 5, y: 2, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "question": Patch(x: 3, y: 3, rows: [".ZZ.", "Z..Z", "...Z", "..Z.", ".Z..", "....", ".Z.."]),
            ]
        )
    )

    /// 猫耳
    static let neko = Look(
        icon: Layers(
            base: [
                "....54455.....55445....55445....",
                "....544445555544445555544445....",
                "....544P4444444444444444P445....",
                ".....54PP44444499944444PP445....",
                ".....54P4449999444999444P45.....",
                ".....5444499444444444944445.....",
                "....544449444444444444944445....",
                "....544494444444444444494445....",
                "...54444444444444444444444445...",
                "...54444444444444444444444445...",
                "...54444444444444444444444445...",
                "..5444444444444444444444444445..",
                "..54444444s44s444444s444444445..",
                "..54444444S44S44ss4sSs4s444445..",
                "...54444ssSssSs4SSsSSSsS44445...",
                "...54444SSSSSSSsSSSSSSSS44445...",
                "..544444SSSSSSSSSSSSSSSS444445..",
                "..544444SSSSSSSSSSSSSSSS444445..",
                "..544444SSSSSSSSSSSSSSSS444445..",
                "..544444SSSSSSSSSSSSSSSS444445..",
                "..5444445SSSSSSSSSSSSSSS444445..",
                "..5444445PPPSSSSSSSSPPP5444445..",
                "..54444455SSSSSSSSSSSS55444445..",
                "..544444575SSSSSSSSSS575444445..",
                ".54444445775SSSSSSSS57754444445.",
                ".544444457775SSSSSS577754444445.",
                ".544444457777755557777754444445.",
                ".54444445777QQQQQQQQ77774444445.",
                ".5444444QqQQQQQQQQQQQQqQ4444445.",
                ".544444qqQQQ666GG666QQQqqQ44445.",
                ".5444QqQQQQQQ66QQ66QQQQQQqQ4445.",
                ".5444qQQQQQQQQQQQQQQQQQQQQqQ445.",
            ],
            eyes: [
                "open": Patch(x: 10, y: 16, rows: [".555....555.", "5W00....0W05", "0W30....0W30", "1331....1331", ".22......22."]),
                "sparkle": Patch(x: 10, y: 16, rows: [".555....555.", "5W00....0W05", "WWW0....WWW0", "1W31....1W31", ".22......22."]),
                "tired": Patch(x: 10, y: 17, rows: ["5555....5555", "0W30....0W30", "1331....1331", ".22......22."]),
                "cry": Patch(x: 10, y: 17, rows: ["55........55", "..55....55..", "55........55"]),
                "closed": Patch(x: 10, y: 18, rows: ["5..5....5..5", ".55......55."]),
                "happy": Patch(x: 10, y: 17, rows: [".55......55.", "5..5....5..5"]),
            ],
            mouths: [
                "open": Patch(x: 15, y: 22, rows: ["MM", "MM"]),
                "wavy": Patch(x: 15, y: 23, rows: ["MM"]),
                "o": Patch(x: 15, y: 23, rows: ["MM"]),
            ],
            extras: [
                "starBig": Patch(x: 1, y: 2, rows: [".Y.", "YYY", ".Y."]),
                "starSmall": Patch(x: 2, y: 3, rows: ["Y"]),
                "sweatA": Patch(x: 3, y: 11, rows: [".X", "XX", "XX"]),
                "sweatB": Patch(x: 3, y: 12, rows: [".X", "XX", "XX"]),
                "tearsA": Patch(x: 10, y: 20, rows: ["X..........X", "X..........X"]),
                "tearsB": Patch(x: 10, y: 21, rows: ["X..........X", "X..........X"]),
                "zzzA": Patch(x: 0, y: 2, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "zzzB": Patch(x: 1, y: 0, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "question": Patch(x: 1, y: 1, rows: ["ZZ.", "..Z", ".Z.", "...", ".Z."]),
            ]
        ),
        portrait: Layers(
            base: [
                "................................................................",
                "...............55...............55.............55...............",
                "..............54455............5445..........55445..............",
                "..............54444555....555554455555....55544445..............",
                "..............544444445555444444444444555544444445..............",
                "..............544PP44444444444444444444444444PP445..............",
                "..............544PPPP4444444444444444444444PPPP445..............",
                "..............544PPP444444449999999944444444PPP445..............",
                "..............544PP44444499999944999999444444PP445..............",
                "..............544P4444999944444444444499994444P445..............",
                "...............54P4444994444444444444444994444P445..............",
                "...............54444499444444444444444444994444445..............",
                "..............544444994444444444444444444499444445..............",
                ".............54444499444444444444444444444499444445.............",
                ".............54444444444444444444444444444444444445.............",
                "............5444444444444444444444444444444444444445............",
                "............5444444444444444444444444444444444444445............",
                "............5444444444444444444444444444444444444445............",
                "...........544444444444444444444444444444444444444445...........",
                "...........544444444444444444444444444444444444444445...........",
                "...........544444444444444444444444444444444444444445...........",
                "...........54444444444ss4444s4444s4444s4444s444444445...........",
                "...........54444444444Ss444sS4444Ss444Ss444S444444445...........",
                "...........544444444s4SSs44SSs44sSS44sSSs4sS444444445...........",
                "...........544444444SsSSSssSSS44SSSssSSSSsSS444444445...........",
                "...........544444444SSSSSSSSSSs4SSSSSSSSSSSS444444445...........",
                "...........544444444SSSSSSSSSSSsSSSSSSSSSSSS444444445...........",
                "...........544444444SSSSSSSSSSSSSSSSSSSSSSSS444444445...........",
                "...........544444444SSSSSSSSSSSSSSSSSSSSSSSS444444445...........",
                "...........544444444SSSSSSSSSSSSSSSSSSSSSSSS444444445...........",
                "..........5444444444SSSSSSSSSSSSSSSSSSSSSSSS4444444445..........",
                "..........5444444444SSSSSSSSSSSSSSSSSSSSSSSS4444444445..........",
                "..........544444444sSSSSSSSSSSSSSSSSSSSSSSSSs444444445..........",
                "..........544444444SSSSSSSSSSSSSSSSSSSSSSSSSS444444445..........",
                "..........5444444445SSSSSSSSSSSSSSSSSSSSSSSS5444444445..........",
                "..........54444444445PPPPPSSSSSSSSSSSSPPPPP54444444445..........",
                "..........54444444455SPPPSSSSSSSSSSSSSSPPPS55444444445..........",
                "..........5444444445.5SSSSSSSSSSSSSSSSSSSS5.5444444445..........",
                "..........5444444445575SSSSSSSSSSSSSSSSSS5755444444445..........",
                "..........5444444445575SSSSSSSSSSSSSSSSS55755444444445..........",
                ".........5444444444557755SSSSSSSSSSSSSS5577554444444445.........",
                ".........54444444445777755SSSSSSSSSSSS55777754444444445.........",
                ".........5444444444577777755SSSSSSSS5577777754444444445.........",
                ".........5444444444577777777555555557777777754444444445.........",
                ".........5444444444577777777ssssssss7777777754444444445.........",
                ".........54444444445777777QQQQQQQQQQQQ77777754444444445.........",
                ".........5444444444QQQQQQQQQQQQQQQQQQQQQQQQQQ4444444445.........",
                ".........544444444QQqqqQQQQQQQQFFQQQQQQQQqqqQQ444444445.........",
                ".........54444444QQqqQQQQQ6666FffF6666QQQQQqqQQ44444445.........",
                ".........5444444QqqQQbbbbQQ666FGGF6666QQQQQQQqqQ4444445.........",
                ".........544444QbbbbbbbbbQQ666QFFQ666QQQQQQQQQqqQQ44445.........",
                ".........54kbbbbbbbbbbbbbQQ6QQQQQQQQ6QQQQQQQQQQQqqQ4445.........",
                ".........54kbbbbbbbbbbbbbQQQQQQQQQQQQQQQQQQQQQQQOqQ4445.........",
                "........544kkbbbbbbbbbbbbQQQQQQQQQQQQQQQQQQQQQQQOqQ44445........",
                "........544kkbbbbbbbbbbbbbSSQQQQQQQQQQQQQQQQQQQQqqQ44445........",
                "........544kkbbbbbbbbbbbbSSSSQQQQQQQQQQQQQQQQQQQqqQ44445........",
                "........544kkbbbbbbbbbbbbSSSSQQQQQQQQQQQQQQQQQOqqQQQ4445........",
                "........544kkbbbbbFbFbbbbSSSSQQQQQQQQQQQQOqqqqQQQQQQ4445........",
                "........544kkbbbbbFfFbbbSSSSQQQQQQQQQOqqqqQQQQQQQQQQ4445........",
                "........5444kbbbbbfGGFbbSSSSqqqOOqqqqqQQQQQQQQQQQQQQ4445........",
                "........5444kbbbbFfGfFbbbSSQQQQqqQQQQQQQQQQQQQQQQQQQQ445........",
                "........544QkkbbbbFFFbbbbbbQQQQQQQQQQQQQQQQQQQQQQQQQQ445........",
                "........544QkkbbbbbbbbbbbbbQQQQQQQQQQQQQQQQQQQQQQQQQQ445........",
                "........544QkkbbbbbbbbbbbbbQQQQQQQQQQQQQQQQQQQQQQQQQQ445........",
            ],
            eyes: [
                "open": Patch(x: 23, y: 27, rows: [".5555........5555.", "550005......500055", "0WW300......0WW300", "0W3310......0W3310", "113311......113311", ".122W1.......122W1", "..22..........22.."]),
                "sparkle": Patch(x: 23, y: 27, rows: [".5555........5555.", "55W005......50W055", "0WWW30......0WWW30", "00W331......00W331", "113311......113311", ".122W1.......122W1", "..22..........22.."]),
                "tired": Patch(x: 23, y: 29, rows: ["555555......555555", "0W3310......0W3310", "113311......113311", ".122W1.......122W1", "..22..........22.."]),
                "cry": Patch(x: 23, y: 28, rows: ["55..............55", "..55..........55..", "....55......55....", "..55..........55..", "55..............55"]),
                "closed": Patch(x: 23, y: 30, rows: ["5....5......5....5", ".5555........5555."]),
                "happy": Patch(x: 23, y: 29, rows: ["..55..........55..", ".5..5........5..5.", "5....5......5....5"]),
            ],
            mouths: [
                "small": Patch(x: 31, y: 38, rows: ["MM"]),
                "open": Patch(x: 30, y: 38, rows: ["MMMM", "MTTM", ".TT."]),
                "wavy": Patch(x: 30, y: 38, rows: ["MMMM"]),
                "o": Patch(x: 31, y: 38, rows: ["MM", "MM", "MM"]),
            ],
            extras: [
                "starBig": Patch(x: 3, y: 5, rows: ["..Y..", ".YYY.", "YYYYY", ".YYY.", "..Y.."]),
                "starSmall": Patch(x: 4, y: 6, rows: [".Y.", "YYY", ".Y."]),
                "sweatA": Patch(x: 8, y: 18, rows: [".X.", "XXX", "XXX", ".X."]),
                "sweatB": Patch(x: 8, y: 20, rows: [".X.", "XXX", "XXX", ".X."]),
                "tearsA": Patch(x: 25, y: 34, rows: ["X............X.", "XX...........XX", "XX...........XX"]),
                "tearsB": Patch(x: 25, y: 35, rows: ["X............X.", "XX...........XX", "XX...........XX"]),
                "zzzA": Patch(x: 3, y: 5, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "zzzB": Patch(x: 5, y: 2, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "question": Patch(x: 3, y: 3, rows: [".ZZ.", "Z..Z", "...Z", "..Z.", ".Z..", "....", ".Z.."]),
            ]
        )
    )

    /// 青春
    static let youth = Look(
        icon: Layers(
            base: [
                "..............KKllKKKKKKmK......",
                "..........KKKKlllmmmllmmmlKK....",
                ".........KlllllllmmmvvmmmullK...",
                ".......KKlllllluummmllmmmllulK..",
                "......KlllluuuullmmuulllmllluK..",
                ".....KlllluulllllllllullllllllK.",
                "....KllllullllllllllllullllllllK",
                "....KlllullllllllllllllulllllllK",
                "...KllllllYllllllllllllllllllllK",
                "...KlllllYlllllllllllllllllllllK",
                "...KlllllllllllllllllllllllllllK",
                "..KllllllllllllllllllllllllllllK",
                "..KlllllllsllsllllllsllllllllllK",
                "..KlllllllSllSllsslsSslslllllllK",
                "...KllllssSssSslSSsSSSsSlllllllK",
                "...KllllSSSSSSSsSSSSSSSSlllllllK",
                "...KllllSSSSSSSSSSSSSSSSlllllllK",
                "....KlllSSSSSSSSSSSSSSSSlllllllK",
                "....KlllSSSSSSSSSSSSSSSSlllKllK.",
                ".....KllSSSSSSSSSSSSSSSSllKKllK.",
                ".....KllKSSSSSSSSSSSSSSSllKKllK.",
                ".....KllPPPPPSSSSSSPPPPPllKKllK.",
                ".....KllKKSSSSSSSSSSSSKKllKKlK..",
                ".....KllKrKSSSSSSSSSSKrKllKKlK..",
                ".....KllKrrKSSSSSSSSKrrKllK.K...",
                ".....KllKrrrKSSSSSSKrrrKllK.....",
                ".....KlKrrrrrrKKKKrrrrrrKlK.....",
                "......KKrrrrpppppppprrrrKK......",
                "......KKpxppppppppppppxpKK......",
                ".....KpxxpppmmmGGmmmpppxxpK.....",
                "....KpxppppppmmppmmppppppxpK....",
                "...KpxppppppppppppppppppppxpK...",
            ],
            eyes: [
                "open": Patch(x: 10, y: 15, rows: [".KKK....KKK.", "KWccK..KccWK", "cWjjc..cWjjc", "gjjjg..gjjjg", "giiWg..giiWg", ".ii......ii."]),
                "sparkle": Patch(x: 10, y: 15, rows: [".KKK....KKK.", "KWWcK..KcWWK", "WWWjc..cjWWW", "gWjjg..gjjWg", "giiWg..gWiig", ".ii......ii."]),
                "tired": Patch(x: 10, y: 17, rows: ["KKKK....KKKK", "cWjc....cWjc", "gjjg....gjjg", ".ii......ii."]),
                "cry": Patch(x: 10, y: 17, rows: ["KK........KK", "..KK....KK..", "KK........KK"]),
                "closed": Patch(x: 10, y: 18, rows: ["K..K....K..K", ".KK......KK."]),
                "happy": Patch(x: 10, y: 17, rows: [".KK......KK.", "K..K....K..K"]),
            ],
            mouths: [
                "small": Patch(x: 15, y: 23, rows: ["MM"]),
                "open": Patch(x: 15, y: 22, rows: ["MM", "MM"]),
                "wavy": Patch(x: 15, y: 23, rows: ["MM"]),
                "o": Patch(x: 15, y: 23, rows: ["MM"]),
            ],
            extras: [
                "starBig": Patch(x: 1, y: 2, rows: [".Y.", "YYY", ".Y."]),
                "starSmall": Patch(x: 2, y: 3, rows: ["Y"]),
                "sweatA": Patch(x: 3, y: 11, rows: [".X", "XX", "XX"]),
                "sweatB": Patch(x: 3, y: 12, rows: [".X", "XX", "XX"]),
                "tearsA": Patch(x: 10, y: 20, rows: ["X..........X", "X..........X"]),
                "tearsB": Patch(x: 10, y: 21, rows: ["X..........X", "X..........X"]),
                "zzzA": Patch(x: 0, y: 2, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "zzzB": Patch(x: 1, y: 0, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "question": Patch(x: 1, y: 1, rows: ["ZZ.", "..Z", ".Z.", "...", ".Z."]),
            ]
        ),
        portrait: Layers(
            base: [
                "................................................................",
                "................................KKKK........KK..................",
                "...............................KllmmK..KKKKKmmK.................",
                "..........................KKKKKllKmmmKKllllmmmKKK...............",
                ".......................KKKllllllllmmmmlvvlmmmmullK..............",
                ".....................KKlllllllllllmmmmvvvvmmmmlullKK............",
                "....................KlllllllllllllmmmmmvvmmmmmlllullK...........",
                "...................KlllllllluuuuuummmmlllllmmmlllluulK..........",
                "..................KlllllluuuuuullummuuulllllmmlllllluK..........",
                ".................KlllluuuulllllllllllluuuullllllllllulK.........",
                "................KllllluulllllllllllllllluullllllllllullK........",
                "...............KllllluulllllllllllllllllluulllllllllullK........",
                "..............KllllluulllllllllllllllllllluulllllllllllK........",
                ".............KllllluulllllllllllllllllllllluullllllllullK.......",
                ".............KlllllllllllllllllllllllllllllllllllllllullK.......",
                "............KlllllllllYYYllllllllllllllllllllllllllllullK.......",
                "............KlllllllYYYllllllllllllllllllllllllllllllullK.......",
                "............KllllllllllloolllllllllllllllllllllllllllullK.......",
                "...........KlllllllllloollllllllllllllllllllllllllllllllK.......",
                "...........KllllllllllllllllllllllllllllllllllllllllllllK.......",
                "...........KllllllllllllllllllllllllllllllllllllllllllllK.......",
                "...........KllllllllllssllllsllllsllllsllllsllllllllllllK.......",
                "...........KllllllllllSslllsSllllSslllSslllSllllllllllllK.......",
                "...........KllllllllslSSsllSSsllsSSllsSSslsSllllllllllllK.......",
                "...........KllllllllSsSSSssSSSllSSSssSSSSsSSllllllllllllK.......",
                "...........KllllllllSSSSSSSSSSslSSSSSSSSSSSSllllllllllllK.......",
                "............KlllllllSSSSSSSSSSSsSSSSSSSSSSSSllllllllllllK.......",
                "............KlllllllSSSSSSSSSSSSSSSSSSSSSSSSllllllllllllK.......",
                ".............KllllllSSSSSSSSSSSSSSSSSSSSSSSSllllllllllllK.......",
                ".............KllllllSSSSSSSSSSSSSSSSSSSSSSSSllllllKllllK........",
                "..............KlllllSSSSSSSSSSSSSSSSSSSSSSSSlllllKKllllK........",
                "..............KlllllSSSSSSSSSSSSSSSSSSSSSSSSlllllKKllllK........",
                "..............KllllsSSSSSSSSSSSSSSSSSSSSSSSSsllllKKllllK........",
                "..............KllllSSSSSSSSSSSSSSSSSSSSSSSSSSllllKKlllK.........",
                "...............KlllKSSPPPSSSSSSSSSSSSSSPPPSSKlllK.KlllK.........",
                "...............KllllPPPPPPPSSSSSSSSSSPPPPPPPllllK.KlllK.........",
                "...............KlllKKPPPPPSSSSSSSSSSSSPPPPPKKlllK.KllK..........",
                "...............KlllK.KSSSSSSSSSSSSSSSSSSSSK.KlllK.KllK..........",
                "...............KlllKKrKSSSSSSSSSSSSSSSSSSKrKKlllK.KlK...........",
                "...............KlllKrrKSSSSSSSSSSSSSSSSSKKrrKlllK.KlK...........",
                "...............KlllKrrrKKSSSSSSSSSSSSSSKKrrrKlllKKlK............",
                "...............KlllKrrrrKKSSSSSSSSSSSSKKrrrrKlllK.K.............",
                "...............KllKKrrrrrrKKSSSSSSSSKKrrrrrrKKllK...............",
                "...............KllKKrrrrrrrrKKKKKKKKrrrrrrrrKKllK...............",
                "...............KllKKrrrrrrrrssssssssrrrrrrrrKKllK...............",
                "................KK.KrrrrrrpppppppppppprrrrrrK.KK................",
                "..................KppppppppppppppppppppppppppK..................",
                ".................KppxxxppppppppFFppppppppxxxppK.................",
                "................KppxxpppppmmmmFffFmmmmpppppxxppK................",
                "..............KKpxxppbbbbppmmmFGGFmmmmpppppppxxpKK..............",
                "...........KKKppbbbbbbbbbppmmmpFFpmmmpppppppppxxppK.............",
                "..........KkbbbbbbbbbbbbbppmppppppppmpppppppppppxxpK............",
                "..........KkbbbbbbbbbbbbbpppppppppppppppppppppppoxpK............",
                "..........KkkbbbbbbbbbbbbpppppppppppppppppppppppoxpK............",
                "..........KkkbbbbbbbbbbbbbSSppppppppppppppppppppxxpK............",
                "..........KkkbbbbbbbbbbbbSSSSpppppppppppppppppppxxppK...........",
                "..........KkkbbbbbbbbbbbbSSSSpppppppppppppppppoxxpppK...........",
                "..........KkkbbbbbFbFbbbbSSSSppppppppppppoxxxxppppppK...........",
                "..........KkkbbbbbFfFbbbSSSSpppppppppoxxxxppppppppppK...........",
                "..........KkkbbbbbfGGFbbSSSSxxxooxxxxxppppppppppppppK...........",
                "..........KkkbbbbFfGfFbbbSSppppxxppppppppppppppppppppK..........",
                "..........KpkkbbbbFFFbbbbbbppppppppppppppppppppppppppK..........",
                "..........KpkkbbbbbbbbbbbbbppppppppppppppppppppppppppK..........",
                "..........KpkkbbbbbbbbbbbbbppppppppppppppppppppppppppK..........",
            ],
            eyes: [
                "open": Patch(x: 23, y: 27, rows: [".KKKKK......KKKKK.", "KKccccK....KccccKK", "cWWcjjc....cWWcjjc", "cWWjjjc....cWWjjjc", "gggjjgg....gggjjgg", "ggiiiWg....ggiiiWg", ".iiiii......iiiii.", "..iii........iii.."]),
                "sparkle": Patch(x: 23, y: 27, rows: [".KKKKK......KKKKK.", "KKWcccK....KcccWKK", "cWWWjjc....cjjWWWc", "cWWjjjc....cjjjWWc", "ggWjjgg....ggjjWgg", "ggiiiWg....gWiiigg", ".iiiii......iiiii.", "..iii........iii.."]),
                "tired": Patch(x: 23, y: 29, rows: ["KKKKKK......KKKKKK", "cWjjgc......cWjjgc", "ggjjgg......ggjjgg", ".giiWg.......giiWg", "..ii..........ii.."]),
                "cry": Patch(x: 23, y: 28, rows: ["KK..............KK", "..KK..........KK..", "....KK......KK....", "..KK..........KK..", "KK..............KK"]),
                "closed": Patch(x: 23, y: 30, rows: ["K....K......K....K", ".KKKK........KKKK."]),
                "happy": Patch(x: 23, y: 29, rows: ["..KK..........KK..", ".K..K........K..K.", "K....K......K....K"]),
            ],
            mouths: [
                "small": Patch(x: 30, y: 38, rows: ["MMMM"]),
                "open": Patch(x: 30, y: 38, rows: ["MMMM", "MTTM", ".TT."]),
                "wavy": Patch(x: 30, y: 38, rows: ["MMMM"]),
                "o": Patch(x: 31, y: 38, rows: ["MM", "MM", "MM"]),
            ],
            extras: [
                "starBig": Patch(x: 3, y: 5, rows: ["..Y..", ".YYY.", "YYYYY", ".YYY.", "..Y.."]),
                "starSmall": Patch(x: 4, y: 6, rows: [".Y.", "YYY", ".Y."]),
                "sweatA": Patch(x: 8, y: 18, rows: [".X.", "XXX", "XXX", ".X."]),
                "sweatB": Patch(x: 8, y: 20, rows: [".X.", "XXX", "XXX", ".X."]),
                "tearsA": Patch(x: 25, y: 34, rows: ["X............X.", "XX...........XX", "XX...........XX"]),
                "tearsB": Patch(x: 25, y: 35, rows: ["X............X.", "XX...........XX", "XX...........XX"]),
                "zzzA": Patch(x: 3, y: 5, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "zzzB": Patch(x: 5, y: 2, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "question": Patch(x: 3, y: 3, rows: [".ZZ.", "Z..Z", "...Z", "..Z.", ".Z..", "....", ".Z.."]),
            ]
        )
    )

    /// 魔女
    static let witch = Look(
        icon: Layers(
            base: [
                "...........LR+RRRRRRRRRRRRRL....",
                "..........LRRRRRRRRRRRRRRRRRL...",
                ".........LRRRRRRRRRRRRRRRRRRRL..",
                "..LLLLLLLJUUYUUUUUUUUUURRRRRRRL.",
                ".LRRRRRRRRUURYUUUUUUUUURRRRRRRL.",
                ".LRRRRRRRRRRRRRRRRRRRRRRRRRRRRRL",
                "..LLLJJJJRJRRRRRRRRRRJRRJJJLLRRL",
                "....LJJJ&JJJJJJJJJJJJJJ&JJJL.LRL",
                "...LJJJJJJJJJJJJJJJJJJJJJJJJL.LY",
                "...LJJJJJJJJJJJJJJJJJJJJJJJJLLYY",
                "...LJJJJJJJJJJJJJJJJJJJJJJJJL.LY",
                "..LJJJJJJJJJJJJJJJJJJJJJJJJJJL.L",
                "..LJJJJJJJsJJsJJJJJJsJJJJJJJJL..",
                "..LJJJJJJJSJJSJJssJsSsJsJJJJJL..",
                "...LJJJJssSssSsJSSsSSSsSJJJJL...",
                "...LJJJJSSSSSSSsSSSSSSSSJJJJL...",
                "..LJJJJJSSSSSSSSSSSSSSSSJJJJJL..",
                "..LJJJJJSSSSSSSSSSSSSSSSJJJJJL..",
                "..LJJJJJSSSSSSSSSSSSSSSSJJJJJL..",
                "..LJJJJJSSSSSSSSSSSSSSSSJJJJJL..",
                "..LJJJJJLSSSSSSSSSSSSSSSJJJJJL..",
                "..LJJJJJLPPPSSSSSSSSPPPLJJJJJL..",
                "..LJJJJJLLSSSSSSSSSSSSLLJJJJJL..",
                "..LJJJJJ+$LSSSSSSSSSSL$+JJJJJL..",
                ".LJJJJJJ++$LSSSSSSSSL$++JJJJJJL.",
                ".LJJJJJJ++$$LSSSSSSL$$++JJJJJJL.",
                ".LJJJJJJ+++$$$LLLL$$$+++JJJJJJL.",
                ".LJJJJJJ++++VVVVVVVV++++JJJJJJL.",
                ".LJJJJJJ++++VVVVVVVV++++JJJJJJL.",
                ".LJJJJJ++VVVRRRGGRRRVVV++VJJJJL.",
                ".LJJJV-VVVVVVRRVVRRVVVVVV-VJJJL.",
                ".LJJJ-VVVVVVVVVVVVVVVVVVVV-VJJL.",
            ],
            eyes: [
                "open": Patch(x: 10, y: 16, rows: [".LLL....LLL.", "LWyy....yWyL", "yWIy....yWIy", "zIIz....zIIz", ".DD......DD."]),
                "sparkle": Patch(x: 10, y: 16, rows: [".LLL....LLL.", "LWyy....yWyL", "WWWy....WWWy", "zWIz....zWIz", ".DD......DD."]),
                "tired": Patch(x: 10, y: 17, rows: ["LLLL....LLLL", "yWIy....yWIy", "zIIz....zIIz", ".DD......DD."]),
                "cry": Patch(x: 10, y: 17, rows: ["LL........LL", "..LL....LL..", "LL........LL"]),
                "closed": Patch(x: 10, y: 18, rows: ["L..L....L..L", ".LL......LL."]),
                "happy": Patch(x: 10, y: 17, rows: [".LL......LL.", "L..L....L..L"]),
            ],
            mouths: [
                "open": Patch(x: 15, y: 22, rows: ["MM", "MM"]),
                "wavy": Patch(x: 15, y: 23, rows: ["MM"]),
                "o": Patch(x: 15, y: 23, rows: ["MM"]),
            ],
            extras: [
                "starBig": Patch(x: 1, y: 2, rows: [".Y.", "YYY", ".Y."]),
                "starSmall": Patch(x: 2, y: 3, rows: ["Y"]),
                "sweatA": Patch(x: 3, y: 11, rows: [".X", "XX", "XX"]),
                "sweatB": Patch(x: 3, y: 12, rows: [".X", "XX", "XX"]),
                "tearsA": Patch(x: 10, y: 20, rows: ["X..........X", "X..........X"]),
                "tearsB": Patch(x: 10, y: 21, rows: ["X..........X", "X..........X"]),
                "zzzA": Patch(x: 0, y: 2, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "zzzB": Patch(x: 1, y: 0, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "question": Patch(x: 1, y: 1, rows: ["ZZ.", "..Z", ".Z.", "...", ".Z."]),
            ]
        ),
        portrait: Layers(
            base: [
                "..........................LLR+RRRRRRRRRRRRRRRRLL................",
                ".........................LRR+RRRRRRRRRRRRRRRRRRRLL..............",
                "........................LR++RRRRRRRRRRRRRRRRRRRRRRL.............",
                ".......................LRRRRRRRRRRRRRRRRRRRRRRRRRRRL............",
                ".......................LRRRRRRRRRRRRRRRRRRRRRRRRRRRRL...........",
                ".....................LLRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRL..........",
                "..................LLLJJUUUYYUUUUUUUUUUUUUURRRRRRRRRRRL..........",
                "...........LLLLLLLRRRRRUUUYYUUUUUUUUUUUUUUURRRRRRRRRRRL.........",
                ".........LLRRRRRRRRRRRRUUUYYYUUUUUUUUUUUUUURRRRRRRRRRRL.........",
                "........LRRRRRRRRRRRRRRRRRRYRRRRRRRRRRRRRRRRRRRRRRRRRRRL........",
                ".........LRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRL........",
                "..........LLLLLRJRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRJRLLLRRRRL.......",
                "..............LJJJJJ&&JJJJJJJJJJJJJJJJJJJJ&&JJJJJL..LRRRL.......",
                ".............LJJJJJ&&JJJJJJJJJJJJJJJJJJJJJJ&&JJJJJL..LRRL.......",
                ".............LJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJL...LRL.......",
                "............LJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJL...LYL......",
                "............LJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJL..LYYYL.....",
                "............LJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJL..LYYYL.....",
                "...........LJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJL..LYL......",
                "...........LJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJL...L.......",
                "...........LJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJL...........",
                "...........LJJJJJJJJJJssJJJJsJJJJsJJJJsJJJJsJJJJJJJJL...........",
                "...........LJJJJJJJJJJSsJJJsSJJJJSsJJJSsJJJSJJJJJJJJL...........",
                "...........LJJJJJJJJsJSSsJJSSsJJsSSJJsSSsJsSJJJJJJJJL...........",
                "...........LJJJJJJJJSsSSSssSSSJJSSSssSSSSsSSJJJJJJJJL...........",
                "...........LJJJJJJJJSSSSSSSSSSsJSSSSSSSSSSSSJJJJJJJJL...........",
                "...........LJJJJJJJJSSSSSSSSSSSsSSSSSSSSSSSSJJJJJJJJL...........",
                "...........LJJJJJJJJSSSSSSSSSSSSSSSSSSSSSSSSJJJJJJJJL...........",
                "...........LJJJJJJJJSSSSSSSSSSSSSSSSSSSSSSSSJJJJJJJJL......LL...",
                "...........LJJJJJJJJSSSSSSSSSSSSSSSSSSSSSSSSJJJJJJJJL.....LYYL..",
                "..........LJJJJJJJJJSSSSSSSSSSSSSSSSSSSSSSSSJJJJJJJJJL...LYYYYL.",
                "..........LJJJJJJJJJSSSSSSSSSSSSSSSSSSSSSSSSJJJJJJJJJL....LYLL..",
                "..........LJJJJJJJJsSSSSSSSSSSSSSSSSSSSSSSSSsJJJJJJJJL.....L....",
                "..........LJJJJJJJJSSSSSSSSSSSSSSSSSSSSSSSSSSJJJJJJJJL..........",
                "..........LJJJJJJJJLSSSSSSSSSSSSSSSSSSSSSSSSLJJJJJJJJL..........",
                "..........LJJJJJJJJJLPPPPPSSSSSSSSSSSSPPPPPLJJJJJJJJJL..........",
                "..........LJJJJJJJJLLSPPPSSSSSSSSSSSSSSPPPSLLJJJJJJJJL..........",
                "..........LJJJJJJJJL.LSSSSSSSSSSSSSSSSSSSSL.LJJJJJJJJL..........",
                "...LL.....LJJJJJJJJ+L$LSSSSSSSSSSSSSSSSSSL$L+JJJJJJJJL..........",
                "..LYYL....LJJJJJJJJ++$LSSSSSSSSSSSSSSSSSLL$++JJJJJJJJL..........",
                "..LYYL...LJJJJJJJJJ+++$LLSSSSSSSSSSSSSSLL$+++JJJJJJJJJL.........",
                "...LL....LJJJJJJJJJ+++$$LLSSSSSSSSSSSSLL$$+++JJJJJJJJJL.........",
                ".........LJJJJJJJJJ++++$$$LLSSSSSSSSLL$$$++++JJJJJJJJJL.........",
                ".........LJJJJJJJJJ+++++$$$$LLLLLLLL$$$$+++++JJJJJJJJJL.........",
                ".........LJJJJJJJJJ++++++$$$ssssssss$$$++++++JJJJJJJJJL.........",
                ".........LJJJJJJJJJ+++++++VVVVVVVVVVVV+++++++JJJJJJJJJL.........",
                ".........LJJJJJJJJJV+++++++VVVVVVVVVV+++++++VJJJJJJJJJL.........",
                ".........LJJJJJJJJVV+++++VVVVVVFFVVVVVV+++++VVJJJJJJJJL.........",
                ".........LJJJJJJJVV++VVVVVRRRRFffFRRRRVVVVV++VVJJJJJJJL.........",
                ".........LJJJJJJV++VV####VVRRRFGGFRRRRVVVVVVV++VJJJJJJL.........",
                ".........LJJJJJ##########VVRRRVFFVRRRVVVVVVVVV---VJJJJL.........",
                ".........LJ*#############VVRVVVVVVVVRVVVVVVVVVVV--VJJJL.........",
                ".........LJ*#############VVVVVVVVVVVVVVVVVVVVVVVU-VJJJL.........",
                "........LJJ**############VVVVVVVVVVVVVVVVVVVVVVVU-VJJJJL........",
                "........LJJ**#############SSVVVVVVVVVVVVVVVVVVVV--VJJJJL........",
                "........LJJ**############SSSSVVVVVVVVVVVVVVVVVVV--VJJJJL........",
                "........LJJ**############SSSSVVVVVVVVVVVVVVVVVU--VVVJJJL........",
                "........LJJ**#####F#F####SSSSVVVVVVVVVVVVU----VVVVVVJJJL........",
                "........LJJ**#####FfF###SSSSVVVVVVVVVU----VVVVVVVVVVJJJL........",
                "........LJJJ*#####fGGF##SSSS---UU-----VVVVVVVVVVVVVVJJJL........",
                "........LJJJ*####FfGfF###SSVVVV--VVVVVVVVVVVVVVVVVVVVJJL........",
                "........LJJV**####FFF######VVVVVVVVVVVVVVVVVVVVVVVVVVJJL........",
                "........LJJV**#############VVVVVVVVVVVVVVVVVVVVVVVVVVJJL........",
                "........LJJV**#############VVVVVVVVVVVVVVVVVVVVVVVVVVJJL........",
            ],
            eyes: [
                "open": Patch(x: 23, y: 27, rows: [".LLLL........LLLL.", "LLyyyL......LyyyLL", "yWWIyy......yWWIyy", "yWIIzy......yWIIzy", "zzIIzz......zzIIzz", ".zDDWz.......zDDWz", "..DD..........DD.."]),
                "sparkle": Patch(x: 23, y: 27, rows: [".LLLL........LLLL.", "LLWyyL......LyWyLL", "yWWWIy......yWWWIy", "yyWIIz......yyWIIz", "zzIIzz......zzIIzz", ".zDDWz.......zDDWz", "..DD..........DD.."]),
                "tired": Patch(x: 23, y: 29, rows: ["LLLLLL......LLLLLL", "yWIIzy......yWIIzy", "zzIIzz......zzIIzz", ".zDDWz.......zDDWz", "..DD..........DD.."]),
                "cry": Patch(x: 23, y: 28, rows: ["LL..............LL", "..LL..........LL..", "....LL......LL....", "..LL..........LL..", "LL..............LL"]),
                "closed": Patch(x: 23, y: 30, rows: ["L....L......L....L", ".LLLL........LLLL."]),
                "happy": Patch(x: 23, y: 29, rows: ["..LL..........LL..", ".L..L........L..L.", "L....L......L....L"]),
            ],
            mouths: [
                "small": Patch(x: 31, y: 38, rows: ["MM"]),
                "open": Patch(x: 30, y: 38, rows: ["MMMM", "MTTM", ".TT."]),
                "wavy": Patch(x: 30, y: 38, rows: ["MMMM"]),
                "o": Patch(x: 31, y: 38, rows: ["MM", "MM", "MM"]),
            ],
            extras: [
                "starBig": Patch(x: 3, y: 5, rows: ["..Y..", ".YYY.", "YYYYY", ".YYY.", "..Y.."]),
                "starSmall": Patch(x: 4, y: 6, rows: [".Y.", "YYY", ".Y."]),
                "sweatA": Patch(x: 8, y: 18, rows: [".X.", "XXX", "XXX", ".X."]),
                "sweatB": Patch(x: 8, y: 20, rows: [".X.", "XXX", "XXX", ".X."]),
                "tearsA": Patch(x: 25, y: 34, rows: ["X............X.", "XX...........XX", "XX...........XX"]),
                "tearsB": Patch(x: 25, y: 35, rows: ["X............X.", "XX...........XX", "XX...........XX"]),
                "zzzA": Patch(x: 3, y: 5, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "zzzB": Patch(x: 5, y: 2, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "question": Patch(x: 3, y: 3, rows: [".ZZ.", "Z..Z", "...Z", "..Z.", ".Z..", "....", ".Z.."]),
            ]
        )
    )

    /// 龙娘
    static let dragon = Look(
        icon: Layers(
            base: [
                "...@..........@@??@.........@...",
                "..@[@.....@@@@????@@@@.....@[@..",
                "..@`[@@..@????????????@..@@[`@..",
                "...@`[[@@??????(((?????@@[[`@...",
                "...@``[[???((((???(((???[[``@...",
                "....@@`???((?????????(^??`@@....",
                "....@????(???????????^=^???@....",
                "....@???(?????????????^(???@....",
                "...@??????????????????,?????@...",
                "...@????????????????????????@...",
                "..@@????????????????????????@@..",
                ".@S??????????????????????????S@.",
                ".@Sss?????s??s??????s??????ssS@.",
                "..@SS?????S??S??ss?sSs?s???SS@..",
                "..@?S???ssSssSs?SSsSSSsS???S?@..",
                "..@?????SSSSSSSsSSSSSSSS?????@..",
                "...@????SSSSSSSSSSSSSSSS????@...",
                "..@?????SSSSSSSSSSSSSSSS?????@..",
                "..@?????SSSSSSSSSSSSSSSS?????@..",
                "..@?????SSSSSSSSSSSSSSSS?????@..",
                "..@?????@SSSSSSSSSSSSSSS?????@..",
                ".@??????@PPPSSSSSSSSPPP@??????@.",
                ".@??????@@SSSSSSSSSSSS@@??????@.",
                "..@?????@~@SSSSSSSSSS@~@?????@..",
                "..@?????@~~@SSSSSSSS@~~@?????@..",
                "..@?????@~~~@SSSSSS@~~~@?????@..",
                "..@?????@~~~~`@@@@`~~~~@?????@..",
                ".@??????@~~~````````~~~~??????@.",
                ".@??????`[`````^^`````[`??????@.",
                ".@?????[[`````^==^`````[[`????@.",
                ".@???`[````````^^````````[`???@.",
                ".@???[`````````,,`````````[`??@.",
            ],
            eyes: [
                "open": Patch(x: 10, y: 16, rows: [".@@@....@@@.", "@W//..../W/@", "/W</..../W</", ":<<:....:<<:", ".;;......;;."]),
                "sparkle": Patch(x: 10, y: 16, rows: [".@@@....@@@.", "@W//..../W/@", "WWW/....WWW/", ":W<:....:W<:", ".;;......;;."]),
                "tired": Patch(x: 10, y: 17, rows: ["@@@@....@@@@", "/W</..../W</", ":<<:....:<<:", ".;;......;;."]),
                "cry": Patch(x: 10, y: 17, rows: ["@@........@@", "..@@....@@..", "@@........@@"]),
                "closed": Patch(x: 10, y: 18, rows: ["@..@....@..@", ".@@......@@."]),
                "happy": Patch(x: 10, y: 17, rows: [".@@......@@.", "@..@....@..@"]),
            ],
            mouths: [
                "open": Patch(x: 15, y: 22, rows: ["MM", "MM"]),
                "wavy": Patch(x: 15, y: 23, rows: ["MM"]),
                "o": Patch(x: 15, y: 23, rows: ["MM"]),
            ],
            extras: [
                "starBig": Patch(x: 1, y: 2, rows: [".Y.", "YYY", ".Y."]),
                "starSmall": Patch(x: 2, y: 3, rows: ["Y"]),
                "sweatA": Patch(x: 3, y: 11, rows: [".X", "XX", "XX"]),
                "sweatB": Patch(x: 3, y: 12, rows: [".X", "XX", "XX"]),
                "tearsA": Patch(x: 10, y: 20, rows: ["X..........X", "X..........X"]),
                "tearsB": Patch(x: 10, y: 21, rows: ["X..........X", "X..........X"]),
                "zzzA": Patch(x: 0, y: 2, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "zzzB": Patch(x: 1, y: 0, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "question": Patch(x: 1, y: 1, rows: ["ZZ.", "..Z", ".Z.", "...", ".Z."]),
            ]
        ),
        portrait: Layers(
            base: [
                ".........@............................................@.........",
                "........@`@.....................@@...................@`@........",
                "........@`[@...................@??@.................@[`@........",
                ".........@[[@.............@@@@@??@@@@@.............@[[@.........",
                ".........@`[@@.........@@@????????????@@@.........@@[`@.........",
                ".........@``[[@@.....@@??????????????????@@.....@@[[``@.........",
                "..........@`[[[[@@@.@??????????????????????@.@@@[[[[`@..........",
                "..........@```[[[[[@????????((((((((????????@[[[[[```@..........",
                "...........@```[[[[??????((((((??((((((??????[[[[```@...........",
                "............@```[[????((((????????????((((????[[```@............",
                ".............@@[``????((????????????????((^???``[@@.............",
                "...............@`????((??????????????????^=^???`@...............",
                "..............@?????((??????????????????^=^=^????@..............",
                ".............@?????((????????????????????^=^(?????@.............",
                ".............@????????????????????????????^???????@.............",
                "............@?????????????????????????????^????????@............",
                "............@?????????????????????????????,????????@............",
                "............@????????????????????????????,,,???????@............",
                ".........@.@?????????????????????????????,,,????????@.@.........",
                "........@S@@????????????????????????????????????????@@S@........",
                ".........@SS????????????????????????????????????????SS@.........",
                ".........@SSs@????????ss????s????s????s????s??????@sSS@.........",
                "..........@SSSs???????Ss???sS????Ss???Ss???S?????sSSS@..........",
                "...........@Sss?????s?SSs??SSs??sSS??sSSs?sS?????ssS@...........",
                "...........@?Ss?????SsSSSssSSS??SSSssSSSSsSS?????sS?@...........",
                "...........@?SS?????SSSSSSSSSSs?SSSSSSSSSSSS?????SS?@...........",
                "...........@??S?????SSSSSSSSSSSsSSSSSSSSSSSS?????S??@...........",
                "...........@????????SSSSSSSSSSSSSSSSSSSSSSSS????????@...........",
                "...........@????????SSSSSSSSSSSSSSSSSSSSSSSS????????@...........",
                "...........@????????SSSSSSSSSSSSSSSSSSSSSSSS????????@...........",
                "...........@????????SSSSSSSSSSSSSSSSSSSSSSSS????????@...........",
                "...........@????????SSSSSSSSSSSSSSSSSSSSSSSS????????@...........",
                "..@.......@????????sSSSSSSSSSSSSSSSSSSSSSSSSs????????@.......@..",
                ".@!@......@????????SSSSSSSSSSSSSSSSSSSSSSSSSS????????@......@!@.",
                "..@!@.....@????????@SSSSSSSSSSSSSSSSSSSSSSSS@????????@.....@!@..",
                "..@[!@...@??????????@PPPPPSSSSSSSSSSSSPPPPP@??????????@...@![@..",
                "..@[!@...@?????????@@SPPPSSSSSSSSSSSSSSPPPS@@?????????@...@![@..",
                "..@[[!@..@?????????@.@SSSSSSSSSSSSSSSSSSSS@.@?????????@..@![[@..",
                "..@[[!!@..@????????@@~@SSSSSSSSSSSSSSSSSS@~@@????????@..@!![[@..",
                "..@[!![!@.@????????@@~@SSSSSSSSSSSSSSSSS@@~@@????????@.@![!![@..",
                ".@[![![!@.@????????@@~~@@SSSSSSSSSSSSSS@@~~@@????????@.@![![![@.",
                ".@![[[[[!@@????????@~~~~@@SSSSSSSSSSSS@@~~~~@????????@@![[[[[!@.",
                "@![[[[[[[!@????????@~~~~~~@@SSSSSSSS@@~~~~~~@????????@![[[[[[[!@",
                ".@[[![[[[[!????????@~~~~~~~~@@@@@@@@~~~~~~~~@????????![[[[[![[@.",
                "..@[![[[[[?????????@~~~~~~~``````````~~~~~~~@?????????[[[[[![@..",
                "..@[![[[[[?????????@~~~~~~~``````````~~~~~~~@?????????[[[[[![@..",
                "...@![[[[??????????``````````````````````````??????????[[[[!@...",
                "...@[[[[[?????????``[[[````````^^````````[[[``?????????[[[[[@...",
                "..@![[[[[????????``[[`````````^==^`````````[[``????????[[[[[!@..",
                "..@![[[[[???????`[[``||||````^=^^=^``````````[[`???????[[[[[!@..",
                "...@@[[[[[?????`|||||||||`````^==^````````````[[``????[[[[[@@...",
                ".....@@@[[?)|||||||||||||``````^^```````````````[[`???[[@@@.....",
                "........@[[)|||||||||||||``````^^```````````````_[`???[@........",
                ".........@?))||||||||||||``````,,```````````````_[`???@.........",
                ".........@?))|||||||||||||SS``,,,,``````````````[[`???@.........",
                ".........@?))||||||||||||SSSS`,,,,``````````````[[`???@.........",
                "........@??))||||||||||||SSSS`````````````````_[[```???@........",
                "........@??))|||||=|=||||SSSS````````````_[[[[``````???@........",
                ".......@???))|||||='=|||SSSS`````````_[[[[``````````????@.......",
                ".......@????)|||||'>>=||SSSS[[[__[[[[[``````````````????@.......",
                ".......@????)||||='>'=|||SS````[[````````````````````???@.......",
                ".......@???`))||||===||||||``````````````````````````???@.......",
                "........@??`))|||||||||||||``````````````````````````??@........",
                "........@??`))|||||||||||||``````````````````````````??@........",
            ],
            eyes: [
                "open": Patch(x: 23, y: 27, rows: [".@@@@........@@@@.", "@@///@......@///@@", "/WW<//....../WW<//", "/W<<:/....../W<<:/", "::<<::......::<<::", ".:;;W:.......:;;W:", "..;;..........;;.."]),
                "sparkle": Patch(x: 23, y: 27, rows: [".@@@@........@@@@.", "@@W//@......@/W/@@", "/WWW</....../WWW</", "//W<<:......//W<<:", "::<<::......::<<::", ".:;;W:.......:;;W:", "..;;..........;;.."]),
                "tired": Patch(x: 23, y: 29, rows: ["@@@@@@......@@@@@@", "/W<<:/....../W<<:/", "::<<::......::<<::", ".:;;W:.......:;;W:", "..;;..........;;.."]),
                "cry": Patch(x: 23, y: 28, rows: ["@@..............@@", "..@@..........@@..", "....@@......@@....", "..@@..........@@..", "@@..............@@"]),
                "closed": Patch(x: 23, y: 30, rows: ["@....@......@....@", ".@@@@........@@@@."]),
                "happy": Patch(x: 23, y: 29, rows: ["..@@..........@@..", ".@..@........@..@.", "@....@......@....@"]),
            ],
            mouths: [
                "small": Patch(x: 31, y: 38, rows: ["MM"]),
                "open": Patch(x: 30, y: 38, rows: ["MMMM", "MTTM", ".TT."]),
                "wavy": Patch(x: 30, y: 38, rows: ["MMMM"]),
                "o": Patch(x: 31, y: 38, rows: ["MM", "MM", "MM"]),
            ],
            extras: [
                "starBig": Patch(x: 3, y: 5, rows: ["..Y..", ".YYY.", "YYYYY", ".YYY.", "..Y.."]),
                "starSmall": Patch(x: 4, y: 6, rows: [".Y.", "YYY", ".Y."]),
                "sweatA": Patch(x: 8, y: 18, rows: [".X.", "XXX", "XXX", ".X."]),
                "sweatB": Patch(x: 8, y: 20, rows: [".X.", "XXX", "XXX", ".X."]),
                "tearsA": Patch(x: 25, y: 34, rows: ["X............X.", "XX...........XX", "XX...........XX"]),
                "tearsB": Patch(x: 25, y: 35, rows: ["X............X.", "XX...........XX", "XX...........XX"]),
                "zzzA": Patch(x: 3, y: 5, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "zzzB": Patch(x: 5, y: 2, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "question": Patch(x: 3, y: 3, rows: [".ZZ.", "Z..Z", "...Z", "..Z.", ".Z..", "....", ".Z.."]),
            ]
        )
    )
}
