// 由 design/export_swift.py 生成，不要手改。
// 想改宠物：改 design/ 里的 Python 原型，python3 design/pet_pixel.py 出预览图，满意了再运行 python3 design/export_swift.py。

/// 宠物的像素数据：每款形象一张调色板、一张不带五官的底图，加上可以叠上去的眼睛、嘴、小道具。
public enum PetArt {
    struct Patch: Sendable {
        let x: Int
        let y: Int
        let rows: [String]
    }

    struct Layers: Sendable {
        let base: [String]
        let eyes: [String: Patch]
        let mouths: [String: Patch]
        let extras: [String: Patch]
    }

    /// 一款形象：自己的调色板 + 菜单栏头像 32×32（显示成 16pt）+ 面板半身像 64×64
    struct Look: Sendable {
        let palette: PetPalette
        let icon: Layers
        let portrait: Layers
    }

    /// 经典
    static let classic = Look(
        palette: PetPalette([
            "A": 0x7A3510,
            "B": 0xC8661E,
            "C": 0xF5A93B,
            "E": 0x3A1A0A,
            "F": 0xF08A3C,
            "G": 0xE7B04A,
            "H": 0xE8743B,
            "K": 0x4A2A20,
            "M": 0x8A3A2A,
            "N": 0x2B2222,
            "O": 0xE0662A,
            "P": 0xF7A08C,
            "Q": 0xFFF6EA,
            "S": 0xFFE9DB,
            "T": 0xF07F7F,
            "W": 0xFFFFFF,
            "X": 0x7CC8F8,
            "Y": 0xFFD34A,
            "Z": 0x8E9AAF,
            "b": 0x7A3E28,
            "d": 0xC4531F,
            "f": 0xC8561E,
            "h": 0xF8AA70,
            "k": 0x4E261A,
            "q": 0xEAD9C4,
            "s": 0xF6CDB8,
        ]),
        icon: Layers(
            base: [
                "..............KKHHK.............",
                "..........KKKKHHHHKKKK..........",
                ".........KHHHHHHHHHHHHK.KKK.....",
                ".......KKHHHHHHhhhHHHHKKKKKK....",
                "......KHHHHhhhhHHHhhhKKKFFKKK...",
                ".....KHHHHhhHHHHHHHHHKKFGGfKK...",
                "....KHHHHhHHHHHHHHHHHKKFGGfKK...",
                "....KHHHhHHHHHHHHHHHHKKKffKKKKK.",
                "...KHHHHHHHHHHHHHHHHHHKKKKKKKNNK",
                "...KHHHHHHHHHHHHHHHHHHHKKKKKNNK.",
                "...KHHHHHHHHHHHHHHHHHHHHHNHNNNK.",
                "..KHHHHHHHHHHHHHHHHHHHHHHNHNNK..",
                "..KHHHHHHHsHHsHHHHHHsHHHHNHHNK..",
                "..KHHHHHHHSHHSHHssHsSsHsHNNHNNK.",
                "...KHHHHssSssSsHSSsSSSsSHHHHNNK.",
                "...KHHHHSSSSSSSsSSSSSSSSHHHHKK..",
                "..KHHHHHSSSSSSSSSSSSSSSSHHHHHK..",
                "..KHHHHHSSSSSSSSSSSSSSSSHHHHHK..",
                "..KHHHHHSSSSSSSSSSSSSSSSHHHHHK..",
                "..KHHHHHSSSSSSSSSSSSSSSSHHHHHK..",
                "..KHHHHHKSSSSSSSSSSSSSSSHHHHHK..",
                "..KHHHHHKPPPSSSSSSSSPPPKHHHHHK..",
                "..KHHHHHKKSSSSSSSSSSSSKKHHHHHK..",
                "..KHHHHHKdKSSSSSSSSSSKdKHHHHHK..",
                ".KHHHHHHKddKSSSSSSSSKddKHHHHHHK.",
                ".KHHHHHHKdddKSSSSSSKdddKHHHHHHK.",
                ".KHHHHHHKdddddKKKKdddddKHHHHHHK.",
                ".KHHHHHHKdddQQQQQQQQddddHHHHHHK.",
                ".KHHHHHHQqQQQQQQQQQQQQqQHHHHHHK.",
                ".KHHHHHqqQQQNNNGGNNNQQQqqQHHHHK.",
                ".KHHHQqQQQQQQNNQQNNQQQQQQqQHHHK.",
                ".KHHHqQQQQQQQQQQQQQQQQQQQQqQHHK.",
            ],
            eyes: [
                "open": Patch(x: 10, y: 16, rows: [".KKK....KKK.", "KWAA....AWAK", "AWEA....AWEA", "BEEB....BEEB", ".CC......CC."]),
                "sparkle": Patch(x: 10, y: 16, rows: [".KKK....KKK.", "KWAA....AWAK", "WWWA....WWWA", "BWEB....BWEB", ".CC......CC."]),
                "tired": Patch(x: 10, y: 17, rows: ["KKKK....KKKK", "AWEA....AWEA", "BEEB....BEEB", ".CC......CC."]),
                "cry": Patch(x: 10, y: 17, rows: ["KK........KK", "..KK....KK..", "KK........KK"]),
                "closed": Patch(x: 10, y: 18, rows: ["K..K....K..K", ".KK......KK."]),
                "happy": Patch(x: 10, y: 17, rows: [".KK......KK.", "K..K....K..K"]),
            ],
            mouths: [
                "open": Patch(x: 15, y: 22, rows: ["MM", "MM"]),
                "wavy": Patch(x: 15, y: 23, rows: ["MM"]),
                "o": Patch(x: 15, y: 23, rows: ["MM"]),
            ],
            extras: [
                "starBig": Patch(x: 1, y: 2, rows: [".Y.", "YYY", ".Y."]),
                "starSmall": Patch(x: 2, y: 3, rows: ["Y"]),
                "sweatA": Patch(x: 3, y: 11, rows: [".X", "XX", "XX"]),
                "sweatB": Patch(x: 3, y: 12, rows: [".X", "XX", "XX"]),
                "tearsA": Patch(x: 10, y: 20, rows: ["X..........X", "X..........X"]),
                "tearsB": Patch(x: 10, y: 21, rows: ["X..........X", "X..........X"]),
                "zzzA": Patch(x: 0, y: 2, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "zzzB": Patch(x: 1, y: 0, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "question": Patch(x: 1, y: 1, rows: ["ZZ.", "..Z", ".Z.", "...", ".Z."]),
            ]
        ),
        portrait: Layers(
            base: [
                "................................................................",
                "................................KK..............................",
                "...............................KHHK.............................",
                "..........................KKKKKHHKKKKK..........................",
                ".......................KKKHHHHHHHHHHHHKKK.......................",
                ".....................KKHHHHHHHHHHHHHHHHHHKK..KKKK...............",
                "....................KHHHHHHHHHHHHHHHHHHHHHHKKKKKKKK.............",
                "...................KHHHHHHHHhhhhhhhhHHHHHHKKKKKKFKKK............",
                "..................KHHHHHHhhhhhhHHhhhhhhHHKKKKFKFFKKK............",
                ".................KHHHHhhhhHHHHHHHHHHHHhhhKKKKfffFKKKK...........",
                "................KHHHHHhhHHHHHHHHHHHHHHHHKKKFFGGGfFKKK...........",
                "...............KHHHHHhhHHHHHHHHHHHHHHHHHKKKKfGGGfFKKK...........",
                "..............KHHHHHhhHHHHHHHHHHHHHHHHHHKKKFFGGGfFKKK.K.........",
                ".............KHHHHHhhHHHHHHHHHHHHHHHHHHHKKKKKfffFKKKKKNK........",
                ".............KHHHHHHHHHHHHHHHHHHHHHHHHHHHKKKKFKFFKKKNNNK........",
                "............KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHKKKKKKFKKKNNNK........",
                "............KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHKKKKKKKKNNNNK........",
                "............KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHKKKKKNHNNNNK........",
                "...........KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHNHHNHNNNK........",
                "...........KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHNHHNHKNNK........",
                "...........KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHNHHNNKKK.........",
                "...........KHHHHHHHHHHssHHHHsHHHHsHHHHsHHHHsHHHNNHHNNK..........",
                "...........KHHHHHHHHHHSsHHHsSHHHHSsHHHSsHHHSHHHNNHHNNNK.........",
                "...........KHHHHHHHHsHSSsHHSSsHHsSSHHsSSsHsSHHHNNHHHNNK.........",
                "...........KHHHHHHHHSsSSSssSSSHHSSSssSSSSsSSHHHHHHHHNNK.........",
                "...........KHHHHHHHHSSSSSSSSSSsHSSSSSSSSSSSSHHHHHHHHKK..........",
                "...........KHHHHHHHHSSSSSSSSSSSsSSSSSSSSSSSSHHHHHHHHK...........",
                "...........KHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHK...........",
                "...........KHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHK...........",
                "...........KHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHK...........",
                "..........KHHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHHK..........",
                "..........KHHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHHK..........",
                "..........KHHHHHHHHsSSSSSSSSSSSSSSSSSSSSSSSSsHHHHHHHHK..........",
                "..........KHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHK..........",
                "..........KHHHHHHHHKSSSSSSSSSSSSSSSSSSSSSSSSKHHHHHHHHK..........",
                "..........KHHHHHHHHHKPPPPPSSSSSSSSSSSSPPPPPKHHHHHHHHHK..........",
                "..........KHHHHHHHHKKSPPPSSSSSSSSSSSSSSPPPSKKHHHHHHHHK..........",
                "..........KHHHHHHHHK.KSSSSSSSSSSSSSSSSSSSSK.KHHHHHHHHK..........",
                "..........KHHHHHHHHKKdKSSSSSSSSSSSSSSSSSSKdKKHHHHHHHHK..........",
                "..........KHHHHHHHHKKdKSSSSSSSSSSSSSSSSSKKdKKHHHHHHHHK..........",
                ".........KHHHHHHHHHKKddKKSSSSSSSSSSSSSSKKddKKHHHHHHHHHK.........",
                ".........KHHHHHHHHHKddddKKSSSSSSSSSSSSKKddddKHHHHHHHHHK.........",
                ".........KHHHHHHHHHKddddddKKSSSSSSSSKKddddddKHHHHHHHHHK.........",
                ".........KHHHHHHHHHKddddddddKKKKKKKKddddddddKHHHHHHHHHK.........",
                ".........KHHHHHHHHHKddddddddssssssssddddddddKHHHHHHHHHK.........",
                ".........KHHHHHHHHHKddddddQQQQQQQQQQQQddddddKHHHHHHHHHK.........",
                ".........KHHHHHHHHHQQQQQQQQQQQQQQQQQQQQQQQQQQHHHHHHHHHK.........",
                ".........KHHHHHHHHQQqqqQQQQQQQQFFQQQQQQQQqqqQQHHHHHHHHK.........",
                ".........KHHHHHHHQQqqQQQQQNNNNFffFNNNNQQQQQqqQQHHHHHHHK.........",
                ".........KHHHHHHQqqQQbbbbQQNNNFGGFNNNNQQQQQQQqqQHHHHHHK.........",
                ".........KHHHHHQbbbbbbbbbQQNNNQFFQNNNQQQQQQQQQqqQQHHHHK.........",
                ".........KHkbbbbbbbbbbbbbQQNQQQQQQQQNQQQQQQQQQQQqqQHHHK.........",
                ".........KHkbbbbbbbbbbbbbQQQQQQQQQQQQQQQQQQQQQQQOqQHHHK.........",
                "........KHHkkbbbbbbbbbbbbQQQQQQQQQQQQQQQQQQQQQQQOqQHHHHK........",
                "........KHHkkbbbbbbbbbbbbbSSQQQQQQQQQQQQQQQQQQQQqqQHHHHK........",
                "........KHHkkbbbbbbbbbbbbSSSSQQQQQQQQQQQQQQQQQQQqqQHHHHK........",
                "........KHHkkbbbbbbbbbbbbSSSSQQQQQQQQQQQQQQQQQOqqQQQHHHK........",
                "........KHHkkbbbbbFbFbbbbSSSSQQQQQQQQQQQQOqqqqQQQQQQHHHK........",
                "........KHHkkbbbbbFfFbbbSSSSQQQQQQQQQOqqqqQQQQQQQQQQHHHK........",
                "........KHHHkbbbbbfGGFbbSSSSqqqOOqqqqqQQQQQQQQQQQQQQHHHK........",
                "........KHHHkbbbbFfGfFbbbSSQQQQqqQQQQQQQQQQQQQQQQQQQQHHK........",
                "........KHHQkkbbbbFFFbbbbbbQQQQQQQQQQQQQQQQQQQQQQQQQQHHK........",
                "........KHHQkkbbbbbbbbbbbbbQQQQQQQQQQQQQQQQQQQQQQQQQQHHK........",
                "........KHHQkkbbbbbbbbbbbbbQQQQQQQQQQQQQQQQQQQQQQQQQQHHK........",
            ],
            eyes: [
                "open": Patch(x: 23, y: 27, rows: [".KKKK........KKKK.", "KKAAAK......KAAAKK", "AWWEAA......AWWEAA", "AWEEBA......AWEEBA", "BBEEBB......BBEEBB", ".BCCWB.......BCCWB", "..CC..........CC.."]),
                "sparkle": Patch(x: 23, y: 27, rows: [".KKKK........KKKK.", "KKWAAK......KAWAKK", "AWWWEA......AWWWEA", "AAWEEB......AAWEEB", "BBEEBB......BBEEBB", ".BCCWB.......BCCWB", "..CC..........CC.."]),
                "tired": Patch(x: 23, y: 29, rows: ["KKKKKK......KKKKKK", "AWEEBA......AWEEBA", "BBEEBB......BBEEBB", ".BCCWB.......BCCWB", "..CC..........CC.."]),
                "cry": Patch(x: 23, y: 28, rows: ["KK..............KK", "..KK..........KK..", "....KK......KK....", "..KK..........KK..", "KK..............KK"]),
                "closed": Patch(x: 23, y: 30, rows: ["K....K......K....K", ".KKKK........KKKK."]),
                "happy": Patch(x: 23, y: 29, rows: ["..KK..........KK..", ".K..K........K..K.", "K....K......K....K"]),
            ],
            mouths: [
                "small": Patch(x: 31, y: 38, rows: ["MM"]),
                "open": Patch(x: 30, y: 38, rows: ["MMMM", "MTTM", ".TT."]),
                "wavy": Patch(x: 30, y: 38, rows: ["MMMM"]),
                "o": Patch(x: 31, y: 38, rows: ["MM", "MM", "MM"]),
            ],
            extras: [
                "starBig": Patch(x: 3, y: 5, rows: ["..Y..", ".YYY.", "YYYYY", ".YYY.", "..Y.."]),
                "starSmall": Patch(x: 4, y: 6, rows: [".Y.", "YYY", ".Y."]),
                "sweatA": Patch(x: 8, y: 18, rows: [".X.", "XXX", "XXX", ".X."]),
                "sweatB": Patch(x: 8, y: 20, rows: [".X.", "XXX", "XXX", ".X."]),
                "tearsA": Patch(x: 25, y: 34, rows: ["X............X.", "XX...........XX", "XX...........XX"]),
                "tearsB": Patch(x: 25, y: 35, rows: ["X............X.", "XX...........XX", "XX...........XX"]),
                "zzzA": Patch(x: 3, y: 5, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "zzzB": Patch(x: 5, y: 2, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "question": Patch(x: 3, y: 3, rows: [".ZZ.", "Z..Z", "...Z", "..Z.", ".Z..", "....", ".Z.."]),
            ]
        )
    )

    /// 猫耳
    static let neko = Look(
        palette: PetPalette([
            "A": 0x583084,
            "B": 0x925AC8,
            "C": 0xCCA0F0,
            "E": 0x28143C,
            "F": 0xF08A3C,
            "G": 0xE7B04A,
            "H": 0xE4DEEE,
            "K": 0x463658,
            "M": 0x8A3A2A,
            "N": 0x584078,
            "O": 0xE0662A,
            "P": 0xF7A08C,
            "Q": 0xFFF6EA,
            "S": 0xFFE9DB,
            "T": 0xF07F7F,
            "W": 0xFFFFFF,
            "X": 0x7CC8F8,
            "Y": 0xFFD34A,
            "Z": 0x8E9AAF,
            "b": 0x7A3E28,
            "d": 0xBEB4D2,
            "f": 0xC8561E,
            "h": 0xFCFAFF,
            "k": 0x4E261A,
            "q": 0xEAD9C4,
            "s": 0xF6CDB8,
        ]),
        icon: Layers(
            base: [
                "....KHHKK.....KKHHK....KKHHK....",
                "....KHHHHKKKKKHHHHKKKKKHHHHK....",
                "....KHHPHHHHHHHHHHHHHHHHPHHK....",
                ".....KHPPHHHHHHhhhHHHHHPPHHK....",
                ".....KHPHHHhhhhHHHhhhHHHPHK.....",
                ".....KHHHHhhHHHHHHHHHhHHHHK.....",
                "....KHHHHhHHHHHHHHHHHHhHHHHK....",
                "....KHHHhHHHHHHHHHHHHHHhHHHK....",
                "...KHHHHHHHHHHHHHHHHHHHHHHHHK...",
                "...KHHHHHHHHHHHHHHHHHHHHHHHHK...",
                "...KHHHHHHHHHHHHHHHHHHHHHHHHK...",
                "..KHHHHHHHHHHHHHHHHHHHHHHHHHHK..",
                "..KHHHHHHHsHHsHHHHHHsHHHHHHHHK..",
                "..KHHHHHHHSHHSHHssHsSsHsHHHHHK..",
                "...KHHHHssSssSsHSSsSSSsSHHHHK...",
                "...KHHHHSSSSSSSsSSSSSSSSHHHHK...",
                "..KHHHHHSSSSSSSSSSSSSSSSHHHHHK..",
                "..KHHHHHSSSSSSSSSSSSSSSSHHHHHK..",
                "..KHHHHHSSSSSSSSSSSSSSSSHHHHHK..",
                "..KHHHHHSSSSSSSSSSSSSSSSHHHHHK..",
                "..KHHHHHKSSSSSSSSSSSSSSSHHHHHK..",
                "..KHHHHHKPPPSSSSSSSSPPPKHHHHHK..",
                "..KHHHHHKKSSSSSSSSSSSSKKHHHHHK..",
                "..KHHHHHKdKSSSSSSSSSSKdKHHHHHK..",
                ".KHHHHHHKddKSSSSSSSSKddKHHHHHHK.",
                ".KHHHHHHKdddKSSSSSSKdddKHHHHHHK.",
                ".KHHHHHHKdddddKKKKdddddKHHHHHHK.",
                ".KHHHHHHKdddQQQQQQQQddddHHHHHHK.",
                ".KHHHHHHQqQQQQQQQQQQQQqQHHHHHHK.",
                ".KHHHHHqqQQQNNNGGNNNQQQqqQHHHHK.",
                ".KHHHQqQQQQQQNNQQNNQQQQQQqQHHHK.",
                ".KHHHqQQQQQQQQQQQQQQQQQQQQqQHHK.",
            ],
            eyes: [
                "open": Patch(x: 10, y: 16, rows: [".KKK....KKK.", "KWAA....AWAK", "AWEA....AWEA", "BEEB....BEEB", ".CC......CC."]),
                "sparkle": Patch(x: 10, y: 16, rows: [".KKK....KKK.", "KWAA....AWAK", "WWWA....WWWA", "BWEB....BWEB", ".CC......CC."]),
                "tired": Patch(x: 10, y: 17, rows: ["KKKK....KKKK", "AWEA....AWEA", "BEEB....BEEB", ".CC......CC."]),
                "cry": Patch(x: 10, y: 17, rows: ["KK........KK", "..KK....KK..", "KK........KK"]),
                "closed": Patch(x: 10, y: 18, rows: ["K..K....K..K", ".KK......KK."]),
                "happy": Patch(x: 10, y: 17, rows: [".KK......KK.", "K..K....K..K"]),
            ],
            mouths: [
                "open": Patch(x: 15, y: 22, rows: ["MM", "MM"]),
                "wavy": Patch(x: 15, y: 23, rows: ["MM"]),
                "o": Patch(x: 15, y: 23, rows: ["MM"]),
            ],
            extras: [
                "starBig": Patch(x: 1, y: 2, rows: [".Y.", "YYY", ".Y."]),
                "starSmall": Patch(x: 2, y: 3, rows: ["Y"]),
                "sweatA": Patch(x: 3, y: 11, rows: [".X", "XX", "XX"]),
                "sweatB": Patch(x: 3, y: 12, rows: [".X", "XX", "XX"]),
                "tearsA": Patch(x: 10, y: 20, rows: ["X..........X", "X..........X"]),
                "tearsB": Patch(x: 10, y: 21, rows: ["X..........X", "X..........X"]),
                "zzzA": Patch(x: 0, y: 2, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "zzzB": Patch(x: 1, y: 0, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "question": Patch(x: 1, y: 1, rows: ["ZZ.", "..Z", ".Z.", "...", ".Z."]),
            ]
        ),
        portrait: Layers(
            base: [
                "................................................................",
                "...............KK...............KK.............KK...............",
                "..............KHHKK............KHHK..........KKHHK..............",
                "..............KHHHHKKK....KKKKKHHKKKKK....KKKHHHHK..............",
                "..............KHHHHHHHKKKKHHHHHHHHHHHHKKKKHHHHHHHK..............",
                "..............KHHPPHHHHHHHHHHHHHHHHHHHHHHHHHHPPHHK..............",
                "..............KHHPPPPHHHHHHHHHHHHHHHHHHHHHHPPPPHHK..............",
                "..............KHHPPPHHHHHHHHhhhhhhhhHHHHHHHHPPPHHK..............",
                "..............KHHPPHHHHHHhhhhhhHHhhhhhhHHHHHHPPHHK..............",
                "..............KHHPHHHHhhhhHHHHHHHHHHHHhhhhHHHHPHHK..............",
                "...............KHPHHHHhhHHHHHHHHHHHHHHHHhhHHHHPHHK..............",
                "...............KHHHHHhhHHHHHHHHHHHHHHHHHHhhHHHHHHK..............",
                "..............KHHHHHhhHHHHHHHHHHHHHHHHHHHHhhHHHHHK..............",
                ".............KHHHHHhhHHHHHHHHHHHHHHHHHHHHHHhhHHHHHK.............",
                ".............KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHK.............",
                "............KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHK............",
                "............KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHK............",
                "............KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHK............",
                "...........KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHK...........",
                "...........KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHK...........",
                "...........KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHK...........",
                "...........KHHHHHHHHHHssHHHHsHHHHsHHHHsHHHHsHHHHHHHHK...........",
                "...........KHHHHHHHHHHSsHHHsSHHHHSsHHHSsHHHSHHHHHHHHK...........",
                "...........KHHHHHHHHsHSSsHHSSsHHsSSHHsSSsHsSHHHHHHHHK...........",
                "...........KHHHHHHHHSsSSSssSSSHHSSSssSSSSsSSHHHHHHHHK...........",
                "...........KHHHHHHHHSSSSSSSSSSsHSSSSSSSSSSSSHHHHHHHHK...........",
                "...........KHHHHHHHHSSSSSSSSSSSsSSSSSSSSSSSSHHHHHHHHK...........",
                "...........KHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHK...........",
                "...........KHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHK...........",
                "...........KHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHK...........",
                "..........KHHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHHK..........",
                "..........KHHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHHK..........",
                "..........KHHHHHHHHsSSSSSSSSSSSSSSSSSSSSSSSSsHHHHHHHHK..........",
                "..........KHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHK..........",
                "..........KHHHHHHHHKSSSSSSSSSSSSSSSSSSSSSSSSKHHHHHHHHK..........",
                "..........KHHHHHHHHHKPPPPPSSSSSSSSSSSSPPPPPKHHHHHHHHHK..........",
                "..........KHHHHHHHHKKSPPPSSSSSSSSSSSSSSPPPSKKHHHHHHHHK..........",
                "..........KHHHHHHHHK.KSSSSSSSSSSSSSSSSSSSSK.KHHHHHHHHK..........",
                "..........KHHHHHHHHKKdKSSSSSSSSSSSSSSSSSSKdKKHHHHHHHHK..........",
                "..........KHHHHHHHHKKdKSSSSSSSSSSSSSSSSSKKdKKHHHHHHHHK..........",
                ".........KHHHHHHHHHKKddKKSSSSSSSSSSSSSSKKddKKHHHHHHHHHK.........",
                ".........KHHHHHHHHHKddddKKSSSSSSSSSSSSKKddddKHHHHHHHHHK.........",
                ".........KHHHHHHHHHKddddddKKSSSSSSSSKKddddddKHHHHHHHHHK.........",
                ".........KHHHHHHHHHKddddddddKKKKKKKKddddddddKHHHHHHHHHK.........",
                ".........KHHHHHHHHHKddddddddssssssssddddddddKHHHHHHHHHK.........",
                ".........KHHHHHHHHHKddddddQQQQQQQQQQQQddddddKHHHHHHHHHK.........",
                ".........KHHHHHHHHHQQQQQQQQQQQQQQQQQQQQQQQQQQHHHHHHHHHK.........",
                ".........KHHHHHHHHQQqqqQQQQQQQQFFQQQQQQQQqqqQQHHHHHHHHK.........",
                ".........KHHHHHHHQQqqQQQQQNNNNFffFNNNNQQQQQqqQQHHHHHHHK.........",
                ".........KHHHHHHQqqQQbbbbQQNNNFGGFNNNNQQQQQQQqqQHHHHHHK.........",
                ".........KHHHHHQbbbbbbbbbQQNNNQFFQNNNQQQQQQQQQqqQQHHHHK.........",
                ".........KHkbbbbbbbbbbbbbQQNQQQQQQQQNQQQQQQQQQQQqqQHHHK.........",
                ".........KHkbbbbbbbbbbbbbQQQQQQQQQQQQQQQQQQQQQQQOqQHHHK.........",
                "........KHHkkbbbbbbbbbbbbQQQQQQQQQQQQQQQQQQQQQQQOqQHHHHK........",
                "........KHHkkbbbbbbbbbbbbbSSQQQQQQQQQQQQQQQQQQQQqqQHHHHK........",
                "........KHHkkbbbbbbbbbbbbSSSSQQQQQQQQQQQQQQQQQQQqqQHHHHK........",
                "........KHHkkbbbbbbbbbbbbSSSSQQQQQQQQQQQQQQQQQOqqQQQHHHK........",
                "........KHHkkbbbbbFbFbbbbSSSSQQQQQQQQQQQQOqqqqQQQQQQHHHK........",
                "........KHHkkbbbbbFfFbbbSSSSQQQQQQQQQOqqqqQQQQQQQQQQHHHK........",
                "........KHHHkbbbbbfGGFbbSSSSqqqOOqqqqqQQQQQQQQQQQQQQHHHK........",
                "........KHHHkbbbbFfGfFbbbSSQQQQqqQQQQQQQQQQQQQQQQQQQQHHK........",
                "........KHHQkkbbbbFFFbbbbbbQQQQQQQQQQQQQQQQQQQQQQQQQQHHK........",
                "........KHHQkkbbbbbbbbbbbbbQQQQQQQQQQQQQQQQQQQQQQQQQQHHK........",
                "........KHHQkkbbbbbbbbbbbbbQQQQQQQQQQQQQQQQQQQQQQQQQQHHK........",
            ],
            eyes: [
                "open": Patch(x: 23, y: 27, rows: [".KKKK........KKKK.", "KKAAAK......KAAAKK", "AWWEAA......AWWEAA", "AWEEBA......AWEEBA", "BBEEBB......BBEEBB", ".BCCWB.......BCCWB", "..CC..........CC.."]),
                "sparkle": Patch(x: 23, y: 27, rows: [".KKKK........KKKK.", "KKWAAK......KAWAKK", "AWWWEA......AWWWEA", "AAWEEB......AAWEEB", "BBEEBB......BBEEBB", ".BCCWB.......BCCWB", "..CC..........CC.."]),
                "tired": Patch(x: 23, y: 29, rows: ["KKKKKK......KKKKKK", "AWEEBA......AWEEBA", "BBEEBB......BBEEBB", ".BCCWB.......BCCWB", "..CC..........CC.."]),
                "cry": Patch(x: 23, y: 28, rows: ["KK..............KK", "..KK..........KK..", "....KK......KK....", "..KK..........KK..", "KK..............KK"]),
                "closed": Patch(x: 23, y: 30, rows: ["K....K......K....K", ".KKKK........KKKK."]),
                "happy": Patch(x: 23, y: 29, rows: ["..KK..........KK..", ".K..K........K..K.", "K....K......K....K"]),
            ],
            mouths: [
                "small": Patch(x: 31, y: 38, rows: ["MM"]),
                "open": Patch(x: 30, y: 38, rows: ["MMMM", "MTTM", ".TT."]),
                "wavy": Patch(x: 30, y: 38, rows: ["MMMM"]),
                "o": Patch(x: 31, y: 38, rows: ["MM", "MM", "MM"]),
            ],
            extras: [
                "starBig": Patch(x: 3, y: 5, rows: ["..Y..", ".YYY.", "YYYYY", ".YYY.", "..Y.."]),
                "starSmall": Patch(x: 4, y: 6, rows: [".Y.", "YYY", ".Y."]),
                "sweatA": Patch(x: 8, y: 18, rows: [".X.", "XXX", "XXX", ".X."]),
                "sweatB": Patch(x: 8, y: 20, rows: [".X.", "XXX", "XXX", ".X."]),
                "tearsA": Patch(x: 25, y: 34, rows: ["X............X.", "XX...........XX", "XX...........XX"]),
                "tearsB": Patch(x: 25, y: 35, rows: ["X............X.", "XX...........XX", "XX...........XX"]),
                "zzzA": Patch(x: 3, y: 5, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "zzzB": Patch(x: 5, y: 2, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "question": Patch(x: 3, y: 3, rows: [".ZZ.", "Z..Z", "...Z", "..Z.", ".Z..", "....", ".Z.."]),
            ]
        )
    )

    /// 青春
    static let youth = Look(
        palette: PetPalette([
            "A": 0x1A5C54,
            "B": 0x2E9680,
            "C": 0x82D6B4,
            "E": 0x0E3028,
            "F": 0xF08A3C,
            "G": 0xE7B04A,
            "H": 0xBA7648,
            "K": 0x4A2A20,
            "M": 0x8A3A2A,
            "N": 0xE84054,
            "O": 0x3A64B4,
            "P": 0xF7A08C,
            "Q": 0xFAFCFF,
            "S": 0xFFE9DB,
            "T": 0xF07F7F,
            "W": 0xFFFFFF,
            "X": 0x7CC8F8,
            "Y": 0xFFD34A,
            "Z": 0x8E9AAF,
            "b": 0x7A3E28,
            "d": 0x925630,
            "f": 0xC8561E,
            "h": 0xE8AC76,
            "k": 0x4E261A,
            "n": 0xFC828C,
            "q": 0xC4D4EA,
            "s": 0xF6CDB8,
        ]),
        icon: Layers(
            base: [
                "..............KKHHKKKKKKNK......",
                "..........KKKKHHHNNNHHNNNHKK....",
                ".........KHHHHHHHNNNnnNNNhHHK...",
                ".......KKHHHHHHhhNNNHHNNNHHhHK..",
                "......KHHHHhhhhHHNNhhHHHNHHHhK..",
                ".....KHHHHhhHHHHHHHHHhHHHHHHHHK.",
                "....KHHHHhHHHHHHHHHHHHhHHHHHHHHK",
                "....KHHHhHHHHHHHHHHHHHHhHHHHHHHK",
                "...KHHHHHHYHHHHHHHHHHHHHHHHHHHHK",
                "...KHHHHHYHHHHHHHHHHHHHHHHHHHHHK",
                "...KHHHHHHHHHHHHHHHHHHHHHHHHHHHK",
                "..KHHHHHHHHHHHHHHHHHHHHHHHHHHHHK",
                "..KHHHHHHHsHHsHHHHHHsHHHHHHHHHHK",
                "..KHHHHHHHSHHSHHssHsSsHsHHHHHHHK",
                "...KHHHHssSssSsHSSsSSSsSHHHHHHHK",
                "...KHHHHSSSSSSSsSSSSSSSSHHHHHHHK",
                "...KHHHHSSSSSSSSSSSSSSSSHHHHHHHK",
                "....KHHHSSSSSSSSSSSSSSSSHHHHHHHK",
                "....KHHHSSSSSSSSSSSSSSSSHHHKHHK.",
                ".....KHHSSSSSSSSSSSSSSSSHHKKHHK.",
                ".....KHHKSSSSSSSSSSSSSSSHHKKHHK.",
                ".....KHHPPPPPSSSSSSPPPPPHHKKHHK.",
                ".....KHHKKSSSSSSSSSSSSKKHHKKHK..",
                ".....KHHKdKSSSSSSSSSSKdKHHKKHK..",
                ".....KHHKddKSSSSSSSSKddKHHK.K...",
                ".....KHHKdddKSSSSSSKdddKHHK.....",
                ".....KHKddddddKKKKddddddKHK.....",
                "......KKddddQQQQQQQQddddKK......",
                "......KKQqQQQQQQQQQQQQqQKK......",
                ".....KQqqQQQNNNGGNNNQQQqqQK.....",
                "....KQqQQQQQQNNQQNNQQQQQQqQK....",
                "...KQqQQQQQQQQQQQQQQQQQQQQqQK...",
            ],
            eyes: [
                "open": Patch(x: 10, y: 15, rows: [".KKK....KKK.", "KWAAK..KAAWK", "AWEEA..AWEEA", "BEEEB..BEEEB", "BCCWB..BCCWB", ".CC......CC."]),
                "sparkle": Patch(x: 10, y: 15, rows: [".KKK....KKK.", "KWWAK..KAWWK", "WWWEA..AEWWW", "BWEEB..BEEWB", "BCCWB..BWCCB", ".CC......CC."]),
                "tired": Patch(x: 10, y: 17, rows: ["KKKK....KKKK", "AWEA....AWEA", "BEEB....BEEB", ".CC......CC."]),
                "cry": Patch(x: 10, y: 17, rows: ["KK........KK", "..KK....KK..", "KK........KK"]),
                "closed": Patch(x: 10, y: 18, rows: ["K..K....K..K", ".KK......KK."]),
                "happy": Patch(x: 10, y: 17, rows: [".KK......KK.", "K..K....K..K"]),
            ],
            mouths: [
                "small": Patch(x: 15, y: 23, rows: ["MM"]),
                "open": Patch(x: 15, y: 22, rows: ["MM", "MM"]),
                "wavy": Patch(x: 15, y: 23, rows: ["MM"]),
                "o": Patch(x: 15, y: 23, rows: ["MM"]),
            ],
            extras: [
                "starBig": Patch(x: 1, y: 2, rows: [".Y.", "YYY", ".Y."]),
                "starSmall": Patch(x: 2, y: 3, rows: ["Y"]),
                "sweatA": Patch(x: 3, y: 11, rows: [".X", "XX", "XX"]),
                "sweatB": Patch(x: 3, y: 12, rows: [".X", "XX", "XX"]),
                "tearsA": Patch(x: 10, y: 20, rows: ["X..........X", "X..........X"]),
                "tearsB": Patch(x: 10, y: 21, rows: ["X..........X", "X..........X"]),
                "zzzA": Patch(x: 0, y: 2, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "zzzB": Patch(x: 1, y: 0, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "question": Patch(x: 1, y: 1, rows: ["ZZ.", "..Z", ".Z.", "...", ".Z."]),
            ]
        ),
        portrait: Layers(
            base: [
                "................................................................",
                "................................KKKK........KK..................",
                "...............................KHHNNK..KKKKKNNK.................",
                "..........................KKKKKHHKNNNKKHHHHNNNKKK...............",
                ".......................KKKHHHHHHHHNNNNHnnHNNNNhHHK..............",
                ".....................KKHHHHHHHHHHHNNNNnnnnNNNNHhHHKK............",
                "....................KHHHHHHHHHHHHHNNNNNnnNNNNNHHHhHHK...........",
                "...................KHHHHHHHHhhhhhhNNNNHHHHHNNNHHHHhhHK..........",
                "..................KHHHHHHhhhhhhHHhNNhhhHHHHHNNHHHHHHhK..........",
                ".................KHHHHhhhhHHHHHHHHHHHHhhhhHHHHHHHHHHhHK.........",
                "................KHHHHHhhHHHHHHHHHHHHHHHHhhHHHHHHHHHHhHHK........",
                "...............KHHHHHhhHHHHHHHHHHHHHHHHHHhhHHHHHHHHHhHHK........",
                "..............KHHHHHhhHHHHHHHHHHHHHHHHHHHHhhHHHHHHHHHHHK........",
                ".............KHHHHHhhHHHHHHHHHHHHHHHHHHHHHHhhHHHHHHHHhHHK.......",
                ".............KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhHHK.......",
                "............KHHHHHHHHHYYYHHHHHHHHHHHHHHHHHHHHHHHHHHHHhHHK.......",
                "............KHHHHHHHYYYHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhHHK.......",
                "............KHHHHHHHHHHHOOHHHHHHHHHHHHHHHHHHHHHHHHHHHhHHK.......",
                "...........KHHHHHHHHHHOOHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHK.......",
                "...........KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHK.......",
                "...........KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHK.......",
                "...........KHHHHHHHHHHssHHHHsHHHHsHHHHsHHHHsHHHHHHHHHHHHK.......",
                "...........KHHHHHHHHHHSsHHHsSHHHHSsHHHSsHHHSHHHHHHHHHHHHK.......",
                "...........KHHHHHHHHsHSSsHHSSsHHsSSHHsSSsHsSHHHHHHHHHHHHK.......",
                "...........KHHHHHHHHSsSSSssSSSHHSSSssSSSSsSSHHHHHHHHHHHHK.......",
                "...........KHHHHHHHHSSSSSSSSSSsHSSSSSSSSSSSSHHHHHHHHHHHHK.......",
                "............KHHHHHHHSSSSSSSSSSSsSSSSSSSSSSSSHHHHHHHHHHHHK.......",
                "............KHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHHHHHK.......",
                ".............KHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHHHHHK.......",
                ".............KHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHKHHHHK........",
                "..............KHHHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHHHKKHHHHK........",
                "..............KHHHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHHHKKHHHHK........",
                "..............KHHHHsSSSSSSSSSSSSSSSSSSSSSSSSsHHHHKKHHHHK........",
                "..............KHHHHSSSSSSSSSSSSSSSSSSSSSSSSSSHHHHKKHHHK.........",
                "...............KHHHKSSPPPSSSSSSSSSSSSSSPPPSSKHHHK.KHHHK.........",
                "...............KHHHHPPPPPPPSSSSSSSSSSPPPPPPPHHHHK.KHHHK.........",
                "...............KHHHKKPPPPPSSSSSSSSSSSSPPPPPKKHHHK.KHHK..........",
                "...............KHHHK.KSSSSSSSSSSSSSSSSSSSSK.KHHHK.KHHK..........",
                "...............KHHHKKdKSSSSSSSSSSSSSSSSSSKdKKHHHK.KHK...........",
                "...............KHHHKddKSSSSSSSSSSSSSSSSSKKddKHHHK.KHK...........",
                "...............KHHHKdddKKSSSSSSSSSSSSSSKKdddKHHHKKHK............",
                "...............KHHHKddddKKSSSSSSSSSSSSKKddddKHHHK.K.............",
                "...............KHHKKddddddKKSSSSSSSSKKddddddKKHHK...............",
                "...............KHHKKddddddddKKKKKKKKddddddddKKHHK...............",
                "...............KHHKKddddddddssssssssddddddddKKHHK...............",
                "................KK.KddddddQQQQQQQQQQQQddddddK.KK................",
                "..................KQQQQQQQQQQQQQQQQQQQQQQQQQQK..................",
                ".................KQQqqqQQQQQQQQFFQQQQQQQQqqqQQK.................",
                "................KQQqqQQQQQNNNNFffFNNNNQQQQQqqQQK................",
                "..............KKQqqQQbbbbQQNNNFGGFNNNNQQQQQQQqqQKK..............",
                "...........KKKQQbbbbbbbbbQQNNNQFFQNNNQQQQQQQQQqqQQK.............",
                "..........KkbbbbbbbbbbbbbQQNQQQQQQQQNQQQQQQQQQQQqqQK............",
                "..........KkbbbbbbbbbbbbbQQQQQQQQQQQQQQQQQQQQQQQOqQK............",
                "..........KkkbbbbbbbbbbbbQQQQQQQQQQQQQQQQQQQQQQQOqQK............",
                "..........KkkbbbbbbbbbbbbbSSQQQQQQQQQQQQQQQQQQQQqqQK............",
                "..........KkkbbbbbbbbbbbbSSSSQQQQQQQQQQQQQQQQQQQqqQQK...........",
                "..........KkkbbbbbbbbbbbbSSSSQQQQQQQQQQQQQQQQQOqqQQQK...........",
                "..........KkkbbbbbFbFbbbbSSSSQQQQQQQQQQQQOqqqqQQQQQQK...........",
                "..........KkkbbbbbFfFbbbSSSSQQQQQQQQQOqqqqQQQQQQQQQQK...........",
                "..........KkkbbbbbfGGFbbSSSSqqqOOqqqqqQQQQQQQQQQQQQQK...........",
                "..........KkkbbbbFfGfFbbbSSQQQQqqQQQQQQQQQQQQQQQQQQQQK..........",
                "..........KQkkbbbbFFFbbbbbbQQQQQQQQQQQQQQQQQQQQQQQQQQK..........",
                "..........KQkkbbbbbbbbbbbbbQQQQQQQQQQQQQQQQQQQQQQQQQQK..........",
                "..........KQkkbbbbbbbbbbbbbQQQQQQQQQQQQQQQQQQQQQQQQQQK..........",
            ],
            eyes: [
                "open": Patch(x: 23, y: 27, rows: [".KKKKK......KKKKK.", "KKAAAAK....KAAAAKK", "AWWAEEA....AWWAEEA", "AWWEEEA....AWWEEEA", "BBBEEBB....BBBEEBB", "BBCCCWB....BBCCCWB", ".CCCCC......CCCCC.", "..CCC........CCC.."]),
                "sparkle": Patch(x: 23, y: 27, rows: [".KKKKK......KKKKK.", "KKWAAAK....KAAAWKK", "AWWWEEA....AEEWWWA", "AWWEEEA....AEEEWWA", "BBWEEBB....BBEEWBB", "BBCCCWB....BWCCCBB", ".CCCCC......CCCCC.", "..CCC........CCC.."]),
                "tired": Patch(x: 23, y: 29, rows: ["KKKKKK......KKKKKK", "AWEEBA......AWEEBA", "BBEEBB......BBEEBB", ".BCCWB.......BCCWB", "..CC..........CC.."]),
                "cry": Patch(x: 23, y: 28, rows: ["KK..............KK", "..KK..........KK..", "....KK......KK....", "..KK..........KK..", "KK..............KK"]),
                "closed": Patch(x: 23, y: 30, rows: ["K....K......K....K", ".KKKK........KKKK."]),
                "happy": Patch(x: 23, y: 29, rows: ["..KK..........KK..", ".K..K........K..K.", "K....K......K....K"]),
            ],
            mouths: [
                "small": Patch(x: 30, y: 38, rows: ["MMMM"]),
                "open": Patch(x: 30, y: 38, rows: ["MMMM", "MTTM", ".TT."]),
                "wavy": Patch(x: 30, y: 38, rows: ["MMMM"]),
                "o": Patch(x: 31, y: 38, rows: ["MM", "MM", "MM"]),
            ],
            extras: [
                "starBig": Patch(x: 3, y: 5, rows: ["..Y..", ".YYY.", "YYYYY", ".YYY.", "..Y.."]),
                "starSmall": Patch(x: 4, y: 6, rows: [".Y.", "YYY", ".Y."]),
                "sweatA": Patch(x: 8, y: 18, rows: [".X.", "XXX", "XXX", ".X."]),
                "sweatB": Patch(x: 8, y: 20, rows: [".X.", "XXX", "XXX", ".X."]),
                "tearsA": Patch(x: 25, y: 34, rows: ["X............X.", "XX...........XX", "XX...........XX"]),
                "tearsB": Patch(x: 25, y: 35, rows: ["X............X.", "XX...........XX", "XX...........XX"]),
                "zzzA": Patch(x: 3, y: 5, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "zzzB": Patch(x: 5, y: 2, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "question": Patch(x: 3, y: 3, rows: [".ZZ.", "Z..Z", "...Z", "..Z.", ".Z..", "....", ".Z.."]),
            ]
        )
    )

    /// 魔女
    static let witch = Look(
        palette: PetPalette([
            "A": 0x824E08,
            "B": 0xDEA01C,
            "C": 0xFFE26E,
            "E": 0x3A1C00,
            "F": 0xF08A3C,
            "G": 0xE7B04A,
            "H": 0x5C3A84,
            "K": 0x261636,
            "M": 0x8A3A2A,
            "N": 0x1E162E,
            "O": 0xF2A43C,
            "P": 0xF7A08C,
            "Q": 0x3E2C5C,
            "S": 0xFFE9DB,
            "T": 0xF07F7F,
            "W": 0xFFFFFF,
            "X": 0x7CC8F8,
            "Y": 0xFFD34A,
            "Z": 0x8E9AAF,
            "b": 0x682C96,
            "d": 0x402460,
            "f": 0xC8561E,
            "h": 0x9670C4,
            "k": 0x3E1660,
            "n": 0x4E3A6E,
            "q": 0x281A3E,
            "s": 0xF6CDB8,
        ]),
        icon: Layers(
            base: [
                "...........KNnNNNNNNNNNNNNNK....",
                "..........KNNNNNNNNNNNNNNNNNK...",
                ".........KNNNNNNNNNNNNNNNNNNNK..",
                "..KKKKKKKHOOYOOOOOOOOOONNNNNNNK.",
                ".KNNNNNNNNOONYOOOOOOOOONNNNNNNK.",
                ".KNNNNNNNNNNNNNNNNNNNNNNNNNNNNNK",
                "..KKKHHHHNHNNNNNNNNNNHNNHHHKKNNK",
                "....KHHHhHHHHHHHHHHHHHHhHHHK.KNK",
                "...KHHHHHHHHHHHHHHHHHHHHHHHHK.KY",
                "...KHHHHHHHHHHHHHHHHHHHHHHHHKKYY",
                "...KHHHHHHHHHHHHHHHHHHHHHHHHK.KY",
                "..KHHHHHHHHHHHHHHHHHHHHHHHHHHK.K",
                "..KHHHHHHHsHHsHHHHHHsHHHHHHHHK..",
                "..KHHHHHHHSHHSHHssHsSsHsHHHHHK..",
                "...KHHHHssSssSsHSSsSSSsSHHHHK...",
                "...KHHHHSSSSSSSsSSSSSSSSHHHHK...",
                "..KHHHHHSSSSSSSSSSSSSSSSHHHHHK..",
                "..KHHHHHSSSSSSSSSSSSSSSSHHHHHK..",
                "..KHHHHHSSSSSSSSSSSSSSSSHHHHHK..",
                "..KHHHHHSSSSSSSSSSSSSSSSHHHHHK..",
                "..KHHHHHKSSSSSSSSSSSSSSSHHHHHK..",
                "..KHHHHHKPPPSSSSSSSSPPPKHHHHHK..",
                "..KHHHHHKKSSSSSSSSSSSSKKHHHHHK..",
                "..KHHHHHndKSSSSSSSSSSKdnHHHHHK..",
                ".KHHHHHHnndKSSSSSSSSKdnnHHHHHHK.",
                ".KHHHHHHnnddKSSSSSSKddnnHHHHHHK.",
                ".KHHHHHHnnndddKKKKdddnnnHHHHHHK.",
                ".KHHHHHHnnnnQQQQQQQQnnnnHHHHHHK.",
                ".KHHHHHHnnnnQQQQQQQQnnnnHHHHHHK.",
                ".KHHHHHnnQQQNNNGGNNNQQQnnQHHHHK.",
                ".KHHHQqQQQQQQNNQQNNQQQQQQqQHHHK.",
                ".KHHHqQQQQQQQQQQQQQQQQQQQQqQHHK.",
            ],
            eyes: [
                "open": Patch(x: 10, y: 16, rows: [".KKK....KKK.", "KWAA....AWAK", "AWEA....AWEA", "BEEB....BEEB", ".CC......CC."]),
                "sparkle": Patch(x: 10, y: 16, rows: [".KKK....KKK.", "KWAA....AWAK", "WWWA....WWWA", "BWEB....BWEB", ".CC......CC."]),
                "tired": Patch(x: 10, y: 17, rows: ["KKKK....KKKK", "AWEA....AWEA", "BEEB....BEEB", ".CC......CC."]),
                "cry": Patch(x: 10, y: 17, rows: ["KK........KK", "..KK....KK..", "KK........KK"]),
                "closed": Patch(x: 10, y: 18, rows: ["K..K....K..K", ".KK......KK."]),
                "happy": Patch(x: 10, y: 17, rows: [".KK......KK.", "K..K....K..K"]),
            ],
            mouths: [
                "open": Patch(x: 15, y: 22, rows: ["MM", "MM"]),
                "wavy": Patch(x: 15, y: 23, rows: ["MM"]),
                "o": Patch(x: 15, y: 23, rows: ["MM"]),
            ],
            extras: [
                "starBig": Patch(x: 1, y: 2, rows: [".Y.", "YYY", ".Y."]),
                "starSmall": Patch(x: 2, y: 3, rows: ["Y"]),
                "sweatA": Patch(x: 3, y: 11, rows: [".X", "XX", "XX"]),
                "sweatB": Patch(x: 3, y: 12, rows: [".X", "XX", "XX"]),
                "tearsA": Patch(x: 10, y: 20, rows: ["X..........X", "X..........X"]),
                "tearsB": Patch(x: 10, y: 21, rows: ["X..........X", "X..........X"]),
                "zzzA": Patch(x: 0, y: 2, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "zzzB": Patch(x: 1, y: 0, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "question": Patch(x: 1, y: 1, rows: ["ZZ.", "..Z", ".Z.", "...", ".Z."]),
            ]
        ),
        portrait: Layers(
            base: [
                "..........................KKNnNNNNNNNNNNNNNNNNKK................",
                ".........................KNNnNNNNNNNNNNNNNNNNNNNKK..............",
                "........................KNnnNNNNNNNNNNNNNNNNNNNNNNK.............",
                ".......................KNNNNNNNNNNNNNNNNNNNNNNNNNNNK............",
                ".......................KNNNNNNNNNNNNNNNNNNNNNNNNNNNNK...........",
                ".....................KKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNK..........",
                "..................KKKHHOOOYYOOOOOOOOOOOOOONNNNNNNNNNNK..........",
                "...........KKKKKKKNNNNNOOOYYOOOOOOOOOOOOOOONNNNNNNNNNNK.........",
                ".........KKNNNNNNNNNNNNOOOYYYOOOOOOOOOOOOOONNNNNNNNNNNK.........",
                "........KNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNK........",
                ".........KNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNK........",
                "..........KKKKKNHNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNHNKKKNNNNK.......",
                "..............KHHHHHhhHHHHHHHHHHHHHHHHHHHHhhHHHHHK..KNNNK.......",
                ".............KHHHHHhhHHHHHHHHHHHHHHHHHHHHHHhhHHHHHK..KNNK.......",
                ".............KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHK...KNK.......",
                "............KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHK...KYK......",
                "............KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHK..KYYYK.....",
                "............KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHK..KYYYK.....",
                "...........KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHK..KYK......",
                "...........KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHK...K.......",
                "...........KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHK...........",
                "...........KHHHHHHHHHHssHHHHsHHHHsHHHHsHHHHsHHHHHHHHK...........",
                "...........KHHHHHHHHHHSsHHHsSHHHHSsHHHSsHHHSHHHHHHHHK...........",
                "...........KHHHHHHHHsHSSsHHSSsHHsSSHHsSSsHsSHHHHHHHHK...........",
                "...........KHHHHHHHHSsSSSssSSSHHSSSssSSSSsSSHHHHHHHHK...........",
                "...........KHHHHHHHHSSSSSSSSSSsHSSSSSSSSSSSSHHHHHHHHK...........",
                "...........KHHHHHHHHSSSSSSSSSSSsSSSSSSSSSSSSHHHHHHHHK...........",
                "...........KHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHK...........",
                "...........KHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHK......KK...",
                "...........KHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHK.....KYYK..",
                "..........KHHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHHK...KYYYYK.",
                "..........KHHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHHK....KYKK..",
                "..........KHHHHHHHHsSSSSSSSSSSSSSSSSSSSSSSSSsHHHHHHHHK.....K....",
                "..........KHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHK..........",
                "..........KHHHHHHHHKSSSSSSSSSSSSSSSSSSSSSSSSKHHHHHHHHK..........",
                "..........KHHHHHHHHHKPPPPPSSSSSSSSSSSSPPPPPKHHHHHHHHHK..........",
                "..........KHHHHHHHHKKSPPPSSSSSSSSSSSSSSPPPSKKHHHHHHHHK..........",
                "..........KHHHHHHHHK.KSSSSSSSSSSSSSSSSSSSSK.KHHHHHHHHK..........",
                "...KK.....KHHHHHHHHnKdKSSSSSSSSSSSSSSSSSSKdKnHHHHHHHHK..........",
                "..KYYK....KHHHHHHHHnndKSSSSSSSSSSSSSSSSSKKdnnHHHHHHHHK..........",
                "..KYYK...KHHHHHHHHHnnndKKSSSSSSSSSSSSSSKKdnnnHHHHHHHHHK.........",
                "...KK....KHHHHHHHHHnnnddKKSSSSSSSSSSSSKKddnnnHHHHHHHHHK.........",
                ".........KHHHHHHHHHnnnndddKKSSSSSSSSKKdddnnnnHHHHHHHHHK.........",
                ".........KHHHHHHHHHnnnnnddddKKKKKKKKddddnnnnnHHHHHHHHHK.........",
                ".........KHHHHHHHHHnnnnnndddssssssssdddnnnnnnHHHHHHHHHK.........",
                ".........KHHHHHHHHHnnnnnnnQQQQQQQQQQQQnnnnnnnHHHHHHHHHK.........",
                ".........KHHHHHHHHHQnnnnnnnQQQQQQQQQQnnnnnnnQHHHHHHHHHK.........",
                ".........KHHHHHHHHQQnnnnnQQQQQQFFQQQQQQnnnnnQQHHHHHHHHK.........",
                ".........KHHHHHHHQQnnQQQQQNNNNFffFNNNNQQQQQnnQQHHHHHHHK.........",
                ".........KHHHHHHQnnQQbbbbQQNNNFGGFNNNNQQQQQQQnnQHHHHHHK.........",
                ".........KHHHHHbbbbbbbbbbQQNNNQFFQNNNQQQQQQQQQqqqQHHHHK.........",
                ".........KHkbbbbbbbbbbbbbQQNQQQQQQQQNQQQQQQQQQQQqqQHHHK.........",
                ".........KHkbbbbbbbbbbbbbQQQQQQQQQQQQQQQQQQQQQQQOqQHHHK.........",
                "........KHHkkbbbbbbbbbbbbQQQQQQQQQQQQQQQQQQQQQQQOqQHHHHK........",
                "........KHHkkbbbbbbbbbbbbbSSQQQQQQQQQQQQQQQQQQQQqqQHHHHK........",
                "........KHHkkbbbbbbbbbbbbSSSSQQQQQQQQQQQQQQQQQQQqqQHHHHK........",
                "........KHHkkbbbbbbbbbbbbSSSSQQQQQQQQQQQQQQQQQOqqQQQHHHK........",
                "........KHHkkbbbbbFbFbbbbSSSSQQQQQQQQQQQQOqqqqQQQQQQHHHK........",
                "........KHHkkbbbbbFfFbbbSSSSQQQQQQQQQOqqqqQQQQQQQQQQHHHK........",
                "........KHHHkbbbbbfGGFbbSSSSqqqOOqqqqqQQQQQQQQQQQQQQHHHK........",
                "........KHHHkbbbbFfGfFbbbSSQQQQqqQQQQQQQQQQQQQQQQQQQQHHK........",
                "........KHHQkkbbbbFFFbbbbbbQQQQQQQQQQQQQQQQQQQQQQQQQQHHK........",
                "........KHHQkkbbbbbbbbbbbbbQQQQQQQQQQQQQQQQQQQQQQQQQQHHK........",
                "........KHHQkkbbbbbbbbbbbbbQQQQQQQQQQQQQQQQQQQQQQQQQQHHK........",
            ],
            eyes: [
                "open": Patch(x: 23, y: 27, rows: [".KKKK........KKKK.", "KKAAAK......KAAAKK", "AWWEAA......AWWEAA", "AWEEBA......AWEEBA", "BBEEBB......BBEEBB", ".BCCWB.......BCCWB", "..CC..........CC.."]),
                "sparkle": Patch(x: 23, y: 27, rows: [".KKKK........KKKK.", "KKWAAK......KAWAKK", "AWWWEA......AWWWEA", "AAWEEB......AAWEEB", "BBEEBB......BBEEBB", ".BCCWB.......BCCWB", "..CC..........CC.."]),
                "tired": Patch(x: 23, y: 29, rows: ["KKKKKK......KKKKKK", "AWEEBA......AWEEBA", "BBEEBB......BBEEBB", ".BCCWB.......BCCWB", "..CC..........CC.."]),
                "cry": Patch(x: 23, y: 28, rows: ["KK..............KK", "..KK..........KK..", "....KK......KK....", "..KK..........KK..", "KK..............KK"]),
                "closed": Patch(x: 23, y: 30, rows: ["K....K......K....K", ".KKKK........KKKK."]),
                "happy": Patch(x: 23, y: 29, rows: ["..KK..........KK..", ".K..K........K..K.", "K....K......K....K"]),
            ],
            mouths: [
                "small": Patch(x: 31, y: 38, rows: ["MM"]),
                "open": Patch(x: 30, y: 38, rows: ["MMMM", "MTTM", ".TT."]),
                "wavy": Patch(x: 30, y: 38, rows: ["MMMM"]),
                "o": Patch(x: 31, y: 38, rows: ["MM", "MM", "MM"]),
            ],
            extras: [
                "starBig": Patch(x: 3, y: 5, rows: ["..Y..", ".YYY.", "YYYYY", ".YYY.", "..Y.."]),
                "starSmall": Patch(x: 4, y: 6, rows: [".Y.", "YYY", ".Y."]),
                "sweatA": Patch(x: 8, y: 18, rows: [".X.", "XXX", "XXX", ".X."]),
                "sweatB": Patch(x: 8, y: 20, rows: [".X.", "XXX", "XXX", ".X."]),
                "tearsA": Patch(x: 25, y: 34, rows: ["X............X.", "XX...........XX", "XX...........XX"]),
                "tearsB": Patch(x: 25, y: 35, rows: ["X............X.", "XX...........XX", "XX...........XX"]),
                "zzzA": Patch(x: 3, y: 5, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "zzzB": Patch(x: 5, y: 2, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "question": Patch(x: 3, y: 3, rows: [".ZZ.", "Z..Z", "...Z", "..Z.", ".Z..", "....", ".Z.."]),
            ]
        )
    )

    /// 龙娘
    static let dragon = Look(
        palette: PetPalette([
            "A": 0x503E8C,
            "B": 0x8670C8,
            "C": 0xC4B4F4,
            "E": 0x241C46,
            "F": 0xFFD6C8,
            "G": 0xFAF8FF,
            "H": 0xDAD8EE,
            "K": 0x3A325E,
            "M": 0x8A3A2A,
            "N": 0xC8323E,
            "O": 0xA49CD2,
            "P": 0xF7A08C,
            "Q": 0xFCFCFF,
            "S": 0xFFE9DB,
            "T": 0xF07F7F,
            "W": 0xFFFFFF,
            "X": 0x7CC8F8,
            "Y": 0xFFD34A,
            "Z": 0x8E9AAF,
            "b": 0x685EA4,
            "d": 0xB0ACD4,
            "f": 0x968ECC,
            "h": 0xFCFCFF,
            "k": 0x463E7C,
            "n": 0xEC6868,
            "q": 0xCECCE6,
            "s": 0xF6CDB8,
        ]),
        icon: Layers(
            base: [
                ".......KqK....KKHHK...KqK.......",
                "......KQqKKKKKHHHHKKKKKqQK......",
                "......KQqKHHHHHHHHHHHHKqQK......",
                ".......KQqKHHHHhhhHHHKqQK.......",
                "......KHQqqKhhhHHHhhKqqQHK......",
                ".....KHHKQQqHHHHHHHHqQQKHHK.....",
                "....KHHHHKQHHHHHHHHHHQKHHHHK....",
                "....KHHHhHHHHHHHHHHHHHHhHHHK....",
                "...KHHHHHHHHHHHHHHHHHHHHHHNHK...",
                "...KHHHHHHHHHHHHHHHHHHHHHNFNK...",
                "..KKHHHHHHHHHHHHHHHHHHHHHHNHKK..",
                ".KSHHHHHHHHHHHHHHHHHHHHHHHnHHSK.",
                ".KSssHHHHHsHHsHHHHHHsHHHHHnssSK.",
                "..KSSHHHHHSHHSHHssHsSsHsHHHSSK..",
                "...KSHHHssSssSsHSSsSSSsSHHHSK...",
                "..KHHHHHSSSSSSSsSSSSSSSSHHHHHK..",
                "..KHHHHHSSSSSSSSSSSSSSSSHHHHHK..",
                "..KHHHHHSSSSSSSSSSSSSSSSHHHHHK..",
                "..KHHHHHSSSSSSSSSSSSSSSSHHHHHK..",
                "..KHHHHHSSSSSSSSSSSSSSSSHHHHHK..",
                "..KHHHHHKSSSSSSSSSSSSSSSHHHHHK..",
                "..KHHHHHKPPPSSSSSSSSPPPKHHHHHK..",
                "..KHHHHHKKSSSSSSSSSSSSKKHHHHHK..",
                "..KHHHHHKdKSSSSSSSSSSKdKHHHHHK..",
                ".KHHHHHHKddKSSSSSSSSKddKHHHHHHK.",
                ".KHHHHHHKdddKSSSSSSKdddKHHHHHHK.",
                ".KHHHHHHKddddQKKKKQddddKHHHHHHK.",
                ".KHHHHHHKdddQQQQQQQQddddHHHHHHK.",
                ".KHHHHHHQqQQQQQNNQQQQQqQHHHHHHK.",
                ".KHHHHHqqQQQQQNFFNQQQQQqqQHHHHK.",
                ".KHHHQqQQQQQQQQNNQQQQQQQQqQHHHK.",
                ".KHHHqQQQQQQQQQQQQQQQQQQQQqQHHK.",
            ],
            eyes: [
                "open": Patch(x: 10, y: 16, rows: [".KKK....KKK.", "KWAA....AWAK", "AWEA....AWEA", "BEEB....BEEB", ".CC......CC."]),
                "sparkle": Patch(x: 10, y: 16, rows: [".KKK....KKK.", "KWAA....AWAK", "WWWA....WWWA", "BWEB....BWEB", ".CC......CC."]),
                "tired": Patch(x: 10, y: 17, rows: ["KKKK....KKKK", "AWEA....AWEA", "BEEB....BEEB", ".CC......CC."]),
                "cry": Patch(x: 10, y: 17, rows: ["KK........KK", "..KK....KK..", "KK........KK"]),
                "closed": Patch(x: 10, y: 18, rows: ["K..K....K..K", ".KK......KK."]),
                "happy": Patch(x: 10, y: 17, rows: [".KK......KK.", "K..K....K..K"]),
            ],
            mouths: [
                "open": Patch(x: 15, y: 22, rows: ["MM", "MM"]),
                "wavy": Patch(x: 15, y: 23, rows: ["MM"]),
                "o": Patch(x: 15, y: 23, rows: ["MM"]),
            ],
            extras: [
                "starBig": Patch(x: 1, y: 2, rows: [".Y.", "YYY", ".Y."]),
                "starSmall": Patch(x: 2, y: 3, rows: ["Y"]),
                "sweatA": Patch(x: 3, y: 11, rows: [".X", "XX", "XX"]),
                "sweatB": Patch(x: 3, y: 12, rows: [".X", "XX", "XX"]),
                "tearsA": Patch(x: 10, y: 20, rows: ["X..........X", "X..........X"]),
                "tearsB": Patch(x: 10, y: 21, rows: ["X..........X", "X..........X"]),
                "zzzA": Patch(x: 0, y: 2, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "zzzB": Patch(x: 1, y: 0, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "question": Patch(x: 1, y: 1, rows: ["ZZ.", "..Z", ".Z.", "...", ".Z."]),
            ]
        ),
        portrait: Layers(
            base: [
                "..................K..........................K..................",
                ".................KqK............KK..........KqK.................",
                "................KQqK...........KHHK.........KqQK................",
                "................KqqK......KKKKKHHKKKKK......KqqK................",
                "................KQqK...KKKHHHHHHHHHHHHKKK...KqQK................",
                "................KQqqK.KHHHHHHHHHHHHHHHHHHK.KqqQK................",
                ".................KQqqKHHHHHHHHHHHHHHHHHHHHKqqQK.................",
                ".................KQqqqKHHHHHhhhhhhhhHHHHHKqqqQK.................",
                ".................KQQqqqKKhhhhhhHHhhhhhhKKqqqQQK.................",
                "................KHKqQqqqKKHHHHHHHHHHHHKKqqqQqKHK................",
                "................KHKQQQqqqHHHHHHHHHHHHHHqqqQQQKHK................",
                "...............KHHHKQQQqHHHHHHHHHHHHHHHHqQQQKHHHK...............",
                "..............KHHHHHKQQQHHHHHHHHHHHHHHHHQQQKHHHNHK..............",
                ".............KHHHHHhKKQHHHHHHHHHHHHHHHHHHQKKhHNFNHK.............",
                ".............KHHHHHHHKKHHHHHHHHHHHHHHHHHHKKHHNFNFNK.............",
                "............KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHNFNHHK............",
                "............KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHNHHHK............",
                "............KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHnHHHK............",
                ".........K.KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHnnnHHHK.K.........",
                "........KSKKHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHnnnHHHKKSK........",
                ".........KSSHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHnHHHHSSK.........",
                ".........KSSsKHHHHHHHHssHHHHsHHHHsHHHHsHHHHsHHHHHHKsSSK.........",
                "..........KSSSsHHHHHHHSsHHHsSHHHHSsHHHSsHHHSHHHHHsSSSK..........",
                "...........KSssHHHHHsHSSsHHSSsHHsSSHHsSSsHsSHHHHHssSK...........",
                "...........KHSsHHHHHSsSSSssSSSHHSSSssSSSSsSSHHHHHsSHK...........",
                "...........KHSSHHHHHSSSSSSSSSSsHSSSSSSSSSSSSHHHHHSSHK...........",
                "...........KHHSHHHHHSSSSSSSSSSSsSSSSSSSSSSSSHHHHHSHHK...........",
                "...........KHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHK...........",
                "...........KHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHK...........",
                "...........KHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHK...........",
                "..........KHHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHHK..........",
                "..........KHHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHHK..........",
                "..........KHHHHHHHHsSSSSSSSSSSSSSSSSSSSSSSSSsHHHHHHHHK..........",
                "..........KHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHK..........",
                "..........KHHHHHHHHKSSSSSSSSSSSSSSSSSSSSSSSSKHHHHHHHHK..........",
                "..........KHHHHHHHHHKPPPPPSSSSSSSSSSSSPPPPPKHHHHHHHHHK..........",
                "..........KHHHHHHHHKKSPPPSSSSSSSSSSSSSSPPPSKKHHHHHHHHK..........",
                "..........KHHHHHHHHK.KSSSSSSSSSSSSSSSSSSSSK.KHHHHHHHHK..........",
                "..........KHHHHHHHHKKdKSSSSSSSSSSSSSSSSSSKdKKHHHHHHHHK..........",
                "..........KHHHHHHHHKKdKSSSSSSSSSSSSSSSSSKKdKKHHHHHHHHK..........",
                "..........KHHHHHHHHKKddKKSSSSSSSSSSSSSSKKddKKHHHHHHHHK..........",
                ".........KHHHHHHHHHKddddKKSSSSSSSSSSSSKKddddKHHHHHHHHHK.........",
                ".........KHHHHHHHHHKddddddKKSSSSSSSSKKddddddKHHHHHHHHHK.........",
                ".........KHHHHHHHHHKddddddddKKKKKKKKddddddddKHHHHHHHHHK.........",
                ".........KHHHHHHHHHKdddddddQQQQQQQQQQdddddddKHHHHHHHHHK.........",
                ".........KHHHHHHHHHKdddddddQQQQQQQQQQdddddddKHHHHHHHHHK.........",
                ".........KHHHHHHHHHQQQQQQQQQQQQNNQQQQQQQQQQQQHHHHHHHHHK.........",
                ".........KHHHHHHHHQQqqqQQQQQQQNFFNQQQQQQQqqqQQHHHHHHHHK.........",
                ".........KHHHHHHHQQqqQQQQQQQQQNFFNQQQQQQQQQqqQQHHHHHHHK.........",
                ".........KHHHHHHQqqQQbbbbQQQQQQNNQQQQQQQQQQQQqqQHHHHHHK.........",
                ".........KHHHHHQbbbbbbbbbQQQQQQQQQQQQQQQQQQQQQqqQQHHHHK.........",
                ".........KHkbbbbbbbbbbbbbQQQQQQQQQQQQQQQQQQQQQQQqqQHHHK.........",
                ".........KHkbbbbbbbbbbbbbQQQQQQQQQQQQQQQQQQQQQQQOqQHHHK.........",
                "........KHHkkbbbbbbbbbbbbQQQQQQQQQQQQQQQQQQQQQQQOqQHHHHK........",
                "........KHHkkbbbbbbbbbbbbbSSQQQQQQQQQQQQQQQQQQQQqqQHHHHK........",
                "........KHHkkbbbbbbbbbbbbSSSSQQQQQQQQQQQQQQQQQQQqqQHHHHK........",
                "........KHHkkbbbbbbbbbbbbSSSSQQQQQQQQQQQQQQQQQOqqQQQHHHK........",
                "........KHHkkbbbbbFbFbbbbSSSSQQQQQQQQQQQQOqqqqQQQQQQHHHK........",
                "........KHHkkbbbbbFfFbbbSSSSQQQQQQQQQOqqqqQQQQQQQQQQHHHK........",
                "........KHHHkbbbbbfGGFbbSSSSqqqOOqqqqqQQQQQQQQQQQQQQHHHK........",
                ".........KHHkbbbbFfGfFbbbSSQQQQqqQQQQQQQQQQQQQQQQQQQQHK.........",
                ".........KHQkkbbbbFFFbbbbbbQQQQQQQQQQQQQQQQQQQQQQQQQQHK.........",
                ".........KHQkkbbbbbbbbbbbbbQQQQQQQQQQQQQQQQQQQQQQQQQQHK.........",
                ".........KHQkkbbbbbbbbbbbbbQQQQQQQQQQQQQQQQQQQQQQQQQQHK.........",
            ],
            eyes: [
                "open": Patch(x: 23, y: 27, rows: [".KKKK........KKKK.", "KKAAAK......KAAAKK", "AWWEAA......AWWEAA", "AWEEBA......AWEEBA", "BBEEBB......BBEEBB", ".BCCWB.......BCCWB", "..CC..........CC.."]),
                "sparkle": Patch(x: 23, y: 27, rows: [".KKKK........KKKK.", "KKWAAK......KAWAKK", "AWWWEA......AWWWEA", "AAWEEB......AAWEEB", "BBEEBB......BBEEBB", ".BCCWB.......BCCWB", "..CC..........CC.."]),
                "tired": Patch(x: 23, y: 29, rows: ["KKKKKK......KKKKKK", "AWEEBA......AWEEBA", "BBEEBB......BBEEBB", ".BCCWB.......BCCWB", "..CC..........CC.."]),
                "cry": Patch(x: 23, y: 28, rows: ["KK..............KK", "..KK..........KK..", "....KK......KK....", "..KK..........KK..", "KK..............KK"]),
                "closed": Patch(x: 23, y: 30, rows: ["K....K......K....K", ".KKKK........KKKK."]),
                "happy": Patch(x: 23, y: 29, rows: ["..KK..........KK..", ".K..K........K..K.", "K....K......K....K"]),
            ],
            mouths: [
                "small": Patch(x: 31, y: 38, rows: ["MM"]),
                "open": Patch(x: 30, y: 38, rows: ["MMMM", "MTTM", ".TT."]),
                "wavy": Patch(x: 30, y: 38, rows: ["MMMM"]),
                "o": Patch(x: 31, y: 38, rows: ["MM", "MM", "MM"]),
            ],
            extras: [
                "starBig": Patch(x: 3, y: 5, rows: ["..Y..", ".YYY.", "YYYYY", ".YYY.", "..Y.."]),
                "starSmall": Patch(x: 4, y: 6, rows: [".Y.", "YYY", ".Y."]),
                "sweatA": Patch(x: 8, y: 18, rows: [".X.", "XXX", "XXX", ".X."]),
                "sweatB": Patch(x: 8, y: 20, rows: [".X.", "XXX", "XXX", ".X."]),
                "tearsA": Patch(x: 25, y: 34, rows: ["X............X.", "XX...........XX", "XX...........XX"]),
                "tearsB": Patch(x: 25, y: 35, rows: ["X............X.", "XX...........XX", "XX...........XX"]),
                "zzzA": Patch(x: 3, y: 5, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "zzzB": Patch(x: 5, y: 2, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "question": Patch(x: 3, y: 3, rows: [".ZZ.", "Z..Z", "...Z", "..Z.", ".Z..", "....", ".Z.."]),
            ]
        )
    )

    /// 汉服
    static let hanfu = Look(
        palette: PetPalette([
            "A": 0x682E1C,
            "B": 0xB05C30,
            "C": 0xECA862,
            "E": 0x38160C,
            "F": 0xECBE50,
            "G": 0xECBE50,
            "H": 0x3A3240,
            "K": 0x120C16,
            "M": 0x8A3A2A,
            "N": 0xC82C38,
            "P": 0xF7A08C,
            "Q": 0xFADEDE,
            "S": 0xFFE9DB,
            "T": 0xF07F7F,
            "W": 0xFFFFFF,
            "X": 0x7CC8F8,
            "Y": 0xFFD34A,
            "Z": 0x8E9AAF,
            "b": 0xA02A34,
            "d": 0x26202C,
            "f": 0xBE8228,
            "h": 0x807294,
            "k": 0x6E1A24,
            "q": 0xE2B6BC,
            "s": 0xF6CDB8,
            "w": 0xFFFAF4,
        ]),
        icon: Layers(
            base: [
                ".....KHHHHHK..KKHHK.KHHHHHK.....",
                "....KHhHHHHHKKHHHHKKHHGHHHHK....",
                "....KHHHHHHHHHHHHHHHHHHGHHHK....",
                "....KHHHHHHHHHHhhhHHHHHHGHHK....",
                "....KHNNNNHhhhhHHHhhhHNNNGHK....",
                ".....KHHHHhhHHHHHHHHHhHHHHGK....",
                "....KHHHHhHHHHHHHHHHHHhHHHHGK...",
                "....KHHHhHHHHHHHHHHHHHHhHHHGK...",
                "...KHHHHHHHHHHHHHHHHHHHHHHHHK...",
                "...KHHHHHHHHHHHHHHHHHHHHHHHHNK..",
                "...KHHHHHHHHHHHHHHHHHHHHHHHNNK..",
                "..KHHHHHHHHHHHHHHHHHHHHHHHHHHK..",
                "..KHHHHHHHsHHsHHHHHHsHHHHHHHHK..",
                "..KHHHHHHHSHHSHHssHsSsHsHHHHHK..",
                "...KHHHHssSssSsHSSsSSSsSHHHHK...",
                "...KHHHHSSSSSSSsSSSSSSSSHHHHK...",
                "..KHHHHHSSSSSSSSSSSSSSSSHHHHHK..",
                "..KHHHHHSSSSSSSSSSSSSSSSHHHHHK..",
                "..KHHHHHSSSSSSSSSSSSSSSSHHHHHK..",
                "..KHHHHHSSSSSSSSSSSSSSSSHHHHHK..",
                "..KHHHHHKSSSSSSSSSSSSSSSHHHHHK..",
                "..KHHHHHKPPPSSSSSSSSPPPKHHHHHK..",
                "..KHHHHHKKSSSSSSSSSSSSKKHHHHHK..",
                "..KHHHHHKdKSSSSSSSSSSKdKHHHHHK..",
                ".KHHHHHHKddKSSSSSSSSKddKHHHHHHK.",
                ".KHHHHHHKdddKSSSSSSKdddKHHHHHHK.",
                ".KHHHHHHKdddddKKKKdddddKHHHHHHK.",
                ".KHHHHHHKdddNwwwwwwNddddHHHHHHK.",
                ".KHHHHHHQQQQNNwwwwNNQQQQHHHHHHK.",
                ".KHHHHHQQQQQQNNwwNNQQQQQQQHHHHK.",
                ".KHHHQQQQQQQQQNwwNQQQQQQQQQHHHK.",
                ".KHHqqQQQQQQQQQNNQQQQQQQQQqqHHK.",
            ],
            eyes: [
                "open": Patch(x: 10, y: 16, rows: [".KKK....KKK.", "KWAA....AWAK", "AWEA....AWEA", "BEEB....BEEB", ".CC......CC."]),
                "sparkle": Patch(x: 10, y: 16, rows: [".KKK....KKK.", "KWAA....AWAK", "WWWA....WWWA", "BWEB....BWEB", ".CC......CC."]),
                "tired": Patch(x: 10, y: 17, rows: ["KKKK....KKKK", "AWEA....AWEA", "BEEB....BEEB", ".CC......CC."]),
                "cry": Patch(x: 10, y: 17, rows: ["KK........KK", "..KK....KK..", "KK........KK"]),
                "closed": Patch(x: 10, y: 18, rows: ["K..K....K..K", ".KK......KK."]),
                "happy": Patch(x: 10, y: 17, rows: [".KK......KK.", "K..K....K..K"]),
            ],
            mouths: [
                "open": Patch(x: 15, y: 22, rows: ["MM", "MM"]),
                "wavy": Patch(x: 15, y: 23, rows: ["MM"]),
                "o": Patch(x: 15, y: 23, rows: ["MM"]),
            ],
            extras: [
                "starBig": Patch(x: 1, y: 2, rows: [".Y.", "YYY", ".Y."]),
                "starSmall": Patch(x: 2, y: 3, rows: ["Y"]),
                "sweatA": Patch(x: 3, y: 11, rows: [".X", "XX", "XX"]),
                "sweatB": Patch(x: 3, y: 12, rows: [".X", "XX", "XX"]),
                "tearsA": Patch(x: 10, y: 20, rows: ["X..........X", "X..........X"]),
                "tearsB": Patch(x: 10, y: 21, rows: ["X..........X", "X..........X"]),
                "zzzA": Patch(x: 0, y: 2, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "zzzB": Patch(x: 1, y: 0, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "question": Patch(x: 1, y: 1, rows: ["ZZ.", "..Z", ".Z.", "...", ".Z."]),
            ]
        ),
        portrait: Layers(
            base: [
                "................KKKKKKK..................KKKKKKK................",
                "...............KHHHHHHHK........KK......KHHHHHHHK...............",
                "..............KHHHHhHHHHK......KHHK....KHHHHhHHHHK..............",
                ".............KHHHhhHHHHHHKKKKKKHHKKKKKKHHGhhHHHHHHK.............",
                ".............KHHhHHHHHHHHKHHHHHHHHHHHHKHHGGHHHHHHHK.............",
                ".............KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGHHHHHHK.............",
                ".............KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGHHHHHK.............",
                ".............KHHHHHHHHHHHHHHhhhhhhhhHHHHHHHHHGGHHHK.............",
                "..............KHNNNNNNNHHhhhhhhHHhhhhhhHHNNNNNGGHK..............",
                "..............KHHNNNNNhhhhHHHHHHHHHHHHhhhhNNNNNGGK..............",
                "...............KHHHHHHhhHHHHHHHHHHHHHHHHhhHHHHHHGGK.............",
                "...............KHHHHHhhHHHHHHHHHHHHHHHHHHhhHHHHHKGGK............",
                "..............KHHHHHhhHHHHHHHHHHHHHHHHHHHHhhHHHHHKGK............",
                ".............KHHHHHhhHHHHHHHHHHHHHHHHHHHHHHhhHHHHHK.............",
                ".............KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGK............",
                "............KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGK...........",
                "............KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGK...........",
                "............KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHNNNK..........",
                "...........KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHNNNK..........",
                "...........KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHNK...........",
                "...........KHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHK...........",
                "...........KHHHHHHHHHHssHHHHsHHHHsHHHHsHHHHsHHHHHHHHK...........",
                "...........KHHHHHHHHHHSsHHHsSHHHHSsHHHSsHHHSHHHHHHHHK...........",
                "...........KHHHHHHHHsHSSsHHSSsHHsSSHHsSSsHsSHHHHHHHHK...........",
                "...........KHHHHHHHHSsSSSssSSSHHSSSssSSSSsSSHHHHHHHHK...........",
                "...........KHHHHHHHHSSSSSSSSSSsHSSSSSSSSSSSSHHHHHHHHK...........",
                "...........KHHHHHHHHSSSSSSSSSSSsSSSSSSSSSSSSHHHHHHHHK...........",
                "...........KHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHK...........",
                "...........KHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHK...........",
                "...........KHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHK...........",
                "..........KHHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHHK..........",
                "..........KHHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHHK..........",
                "..........KHHHHHHHHsSSSSSSSSSSSSSSSSSSSSSSSSsHHHHHHHHK..........",
                "..........KHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHK..........",
                "..........KHHHHHHHHKSSSSSSSSSSSSSSSSSSSSSSSSKHHHHHHHHK..........",
                "..........KHHHHHHHHHKPPPPPSSSSSSSSSSSSPPPPPKHHHHHHHHHK..........",
                "..........KHHHHHHHHKKSPPPSSSSSSSSSSSSSSPPPSKKHHHHHHHHK..........",
                "..........KHHHHHHHHK.KSSSSSSSSSSSSSSSSSSSSK.KHHHHHHHHK..........",
                "..........KHHHHHHHHKKdKSSSSSSSSSSSSSSSSSSKdKKHHHHHHHHK..........",
                "..........KHHHHHHHHKKdKSSSSSSSSSSSSSSSSSKKdKKHHHHHHHHK..........",
                ".........KHHHHHHHHHKKddKKSSSSSSSSSSSSSSKKddKKHHHHHHHHHK.........",
                ".........KHHHHHHHHHKddddKKSSSSSSSSSSSSKKddddKHHHHHHHHHK.........",
                ".........KHHHHHHHHHKddddddKKSSSSSSSSKKddddddKHHHHHHHHHK.........",
                ".........KHHHHHHHHHKddddddddKKKKKKKKddddddddKHHHHHHHHHK.........",
                ".........KHHHHHHHHHKddddddddssssssssddddddddKHHHHHHHHHK.........",
                ".........KHHHHHHHHHKdddddNNNwwwwwwwwNNNdddddKHHHHHHHHHK.........",
                ".........KHHHHHHHHHQQQQQQQNNwwwwwwwwNNQQQQQQQHHHHHHHHHK.........",
                ".........KHHHHHHHHQQQQQQQQNNNwwwwwwNNQQQQQQQQQHHHHHHHHK.........",
                ".........KHHHHHHHQQQQQQQQQQNNNwwwwNNNQQQQQQQQQQHHHHHHHK.........",
                ".........KHHHHHHQQQQQbbbbQQQNNwwwwNNQQQQQQQQQQQQHHHHHHK.........",
                ".........KHHHHHQbbbbbbbbbQQQQNNwwNNQQQQQQQQQQQQQQQHHHHK.........",
                ".........KHkbbbbbbbbbbbbbQQQQNNNNNNQQQQQQQQQQQQQQqHHHHK.........",
                ".........KHkbbbbbbbbbbbbbQQQQQNNNNQQQQQQQQQQQQQqqqqHHHK.........",
                "........KHHkkbbbbbbbbbbbbQQQQQNNNQQQQQQQQQQQQQQqqqqHHHHK........",
                "........KHHkkbbbbbbbbbbbbbSSQQNNNNQQQQQQQQQQQQQQqqqHHHHK........",
                "........KHHkkbbbbbbbbbbbbSSSSNNNNNNQQQQQQQQQQQQQqqqHHHHK........",
                "........KHHkkbbbbbbbbbbbbSSSSNNQQNNQQQQQQQQQQQQQqqqqHHHK........",
                "........KHHkkbbbbbFbFbbbbSSSSNQQQQQQQQQQQQQQQQQQqqqqHHHK........",
                "........KHHkkbbbbbFfFbbbSSSSNQQQQQQQQQQQQQQQQQQQqqqqHHHK........",
                "........KHHHkbbbbbfGGFbbSSSSNQQQQQQQQQQQQQQQQQQQQqqqHHHK........",
                "........KHHHkbbbbFfGfFbbbSSQQQQQQQQQQQQQQQQQQQQQQqqqqHHK........",
                "........KHGGkkbbbbFFFbbbbbbQGGGGGGGGGGGGGGGGGGGGGGGGGGHK........",
                "........KHNNkkbbbbbbbbbbbbbQNNNNNNNNNNNNNNNNNNNNNNNNNNHK........",
                "........KHNNkkbbbbbbbbbbbbbQNNNNNNNNNNNNNNNNNNNNNNNNNNHK........",
            ],
            eyes: [
                "open": Patch(x: 23, y: 27, rows: [".KKKK........KKKK.", "KKAAAK......KAAAKK", "AWWEAA......AWWEAA", "AWEEBA......AWEEBA", "BBEEBB......BBEEBB", ".BCCWB.......BCCWB", "..CC..........CC.."]),
                "sparkle": Patch(x: 23, y: 27, rows: [".KKKK........KKKK.", "KKWAAK......KAWAKK", "AWWWEA......AWWWEA", "AAWEEB......AAWEEB", "BBEEBB......BBEEBB", ".BCCWB.......BCCWB", "..CC..........CC.."]),
                "tired": Patch(x: 23, y: 29, rows: ["KKKKKK......KKKKKK", "AWEEBA......AWEEBA", "BBEEBB......BBEEBB", ".BCCWB.......BCCWB", "..CC..........CC.."]),
                "cry": Patch(x: 23, y: 28, rows: ["KK..............KK", "..KK..........KK..", "....KK......KK....", "..KK..........KK..", "KK..............KK"]),
                "closed": Patch(x: 23, y: 30, rows: ["K....K......K....K", ".KKKK........KKKK."]),
                "happy": Patch(x: 23, y: 29, rows: ["..KK..........KK..", ".K..K........K..K.", "K....K......K....K"]),
            ],
            mouths: [
                "small": Patch(x: 31, y: 38, rows: ["MM"]),
                "open": Patch(x: 30, y: 38, rows: ["MMMM", "MTTM", ".TT."]),
                "wavy": Patch(x: 30, y: 38, rows: ["MMMM"]),
                "o": Patch(x: 31, y: 38, rows: ["MM", "MM", "MM"]),
            ],
            extras: [
                "starBig": Patch(x: 3, y: 5, rows: ["..Y..", ".YYY.", "YYYYY", ".YYY.", "..Y.."]),
                "starSmall": Patch(x: 4, y: 6, rows: [".Y.", "YYY", ".Y."]),
                "sweatA": Patch(x: 8, y: 18, rows: [".X.", "XXX", "XXX", ".X."]),
                "sweatB": Patch(x: 8, y: 20, rows: [".X.", "XXX", "XXX", ".X."]),
                "tearsA": Patch(x: 25, y: 34, rows: ["X............X.", "XX...........XX", "XX...........XX"]),
                "tearsB": Patch(x: 25, y: 35, rows: ["X............X.", "XX...........XX", "XX...........XX"]),
                "zzzA": Patch(x: 3, y: 5, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "zzzB": Patch(x: 5, y: 2, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "question": Patch(x: 3, y: 3, rows: [".ZZ.", "Z..Z", "...Z", "..Z.", ".Z..", "....", ".Z.."]),
            ]
        )
    )

    /// 极客
    static let geek = Look(
        palette: PetPalette([
            "A": 0x105C42,
            "B": 0x24A474,
            "C": 0x92ECBA,
            "E": 0x082E20,
            "F": 0x78F0A0,
            "G": 0xBEFAD2,
            "H": 0x58BEB4,
            "K": 0x14303A,
            "M": 0x8A3A2A,
            "N": 0x262A36,
            "O": 0x78F0A0,
            "P": 0xF7A08C,
            "Q": 0x52586A,
            "S": 0xFFE9DB,
            "T": 0xF07F7F,
            "W": 0xFFFFFF,
            "X": 0x7CC8F8,
            "Y": 0xFFD34A,
            "Z": 0x8E9AAF,
            "b": 0x2C303E,
            "d": 0x36928C,
            "f": 0x3CAA6E,
            "h": 0xA8EAE0,
            "k": 0x1A1C26,
            "n": 0x464C5E,
            "q": 0x3C4050,
            "s": 0xF6CDB8,
            "w": 0xECF0F6,
        ]),
        icon: Layers(
            base: [
                "............KKKKHHKK............",
                "..........KKNNNNNNNNKK..........",
                "........KKNNNHHHHHHNNNKK........",
                ".......KNNNHHHHhhhHHHNNNK.......",
                "......KNNHHhhhhHHHhhhHHNNK......",
                ".....KNNHHhhHHHHHHHHHhHHNNK.....",
                "....KHNHHhHHHHHHHHHHHHhHHNHK....",
                "....KNNHhHHHHHHHHHHHHHHhHNNK....",
                "...KHNHHHHHHHHHHHHHHHHHHHHNHK...",
                "...KNNHHHHHHHHHHHHHHHHHHHHNNK...",
                "...KNNHHHHHHHHHHHHHHHHHHHHNNK...",
                "..KHNHHHHHHHHHHHHHHHHHHHHHHNHK..",
                "..KHNHHHHHsHHsHHHHHHsHHHHHHNHK..",
                "..KNNNHHHHSHHSHHssHsSsHsHHNNNK..",
                ".KNNnNNHssSssSsHSSsSSSsSHNNnNNK.",
                ".KOOnnNHSSSSSSSsSSSSSSSSHNnnOOK.",
                ".KOOnnNHSSSSSSSSSSSSSSSSHNnnOOK.",
                ".KNnnNNHSSSSSSSSSSSSSSSSHNNnnNK.",
                ".KNNNNHHSSSSSSSSSSSSSSSSHHNNNNK.",
                "..KNNHHHSSSSSSSSSSSSSSSSHHHNNK..",
                "..KHHHHHKSSSSSSSSSSSSSSSHHHHHK..",
                "..KHHHHHKPPPSSSSSSSSPPPKHHHHHK..",
                "..KHHHHHKKSSSSSSSSSSSSKKHHHHHK..",
                "..KHHHHHKdKSSSSSSSSSSKdKHHHHHK..",
                ".KHHHHHHKddKSSSSSSSSKddKHHHHHHK.",
                ".KHHHHHHKdddKSSSSSSKdddKHHHHHHK.",
                ".KHHHHHHKdddddKKKKdddddKHHHHHHK.",
                ".KHHHHHqqqqqqqqqqqqqqqqqqHHHHHK.",
                ".KHHHHqqqqqqqqqqqqqqqqqqqqHHHHK.",
                ".KHHHHqqqqqqqqqqqqqqqqqqqqHHHHK.",
                ".KHHHqqqqqqqqqwQQwqqqqqqqqqHHHK.",
                ".KHHqqqqqqqqqQwQQQQqqqqqqqqqHHK.",
            ],
            eyes: [
                "open": Patch(x: 10, y: 16, rows: [".KKK....KKK.", "KWAA....AWAK", "AWEA....AWEA", "BEEB....BEEB", ".CC......CC."]),
                "sparkle": Patch(x: 10, y: 16, rows: [".KKK....KKK.", "KWAA....AWAK", "WWWA....WWWA", "BWEB....BWEB", ".CC......CC."]),
                "tired": Patch(x: 10, y: 17, rows: ["KKKK....KKKK", "AWEA....AWEA", "BEEB....BEEB", ".CC......CC."]),
                "cry": Patch(x: 10, y: 17, rows: ["KK........KK", "..KK....KK..", "KK........KK"]),
                "closed": Patch(x: 10, y: 18, rows: ["K..K....K..K", ".KK......KK."]),
                "happy": Patch(x: 10, y: 17, rows: [".KK......KK.", "K..K....K..K"]),
            ],
            mouths: [
                "open": Patch(x: 15, y: 22, rows: ["MM", "MM"]),
                "wavy": Patch(x: 15, y: 23, rows: ["MM"]),
                "o": Patch(x: 15, y: 23, rows: ["MM"]),
            ],
            extras: [
                "starBig": Patch(x: 1, y: 2, rows: [".Y.", "YYY", ".Y."]),
                "starSmall": Patch(x: 2, y: 3, rows: ["Y"]),
                "sweatA": Patch(x: 3, y: 11, rows: [".X", "XX", "XX"]),
                "sweatB": Patch(x: 3, y: 12, rows: [".X", "XX", "XX"]),
                "tearsA": Patch(x: 10, y: 20, rows: ["X..........X", "X..........X"]),
                "tearsB": Patch(x: 10, y: 21, rows: ["X..........X", "X..........X"]),
                "zzzA": Patch(x: 0, y: 2, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "zzzB": Patch(x: 1, y: 0, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "question": Patch(x: 1, y: 1, rows: ["ZZ.", "..Z", ".Z.", "...", ".Z."]),
            ]
        ),
        portrait: Layers(
            base: [
                "................................................................",
                "................................KK..............................",
                "...........................KKKKKHHKKK...........................",
                "........................KKKNNNNNNNNNNKKK........................",
                "......................KKNNNNNNNNNNNNNNNNKK......................",
                ".....................KNNNNNHHHHHHHHHHNNNNNK.....................",
                "...................KKNNNNHHHHHHHHHHHHHHNNNNKK...................",
                "..................KNNNNHHHHHhhhhhhhhHHHHHNNNNK..................",
                ".................KNNNHHHHhhhhhhHHhhhhhhHHHHNNNK.................",
                "................KNNNHHhhhhHHHHHHHHHHHHhhhhHHNNNK................",
                "................KNNHHHhhHHHHHHHHHHHHHHHHhhHHHNNK................",
                "...............KNNHHHhhHHHHHHHHHHHHHHHHHHhhHHHNNK...............",
                "..............KNNNHHhhHHHHHHHHHHHHHHHHHHHHhhHHNNNK..............",
                ".............KHNNHHhhHHHHHHHHHHHHHHHHHHHHHHhhHHNNHK.............",
                ".............KNNNHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHNNNK.............",
                "............KHNNHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHNNHK............",
                "............KHNNHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHNNHK............",
                "............KNNHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHNNK............",
                "...........KHNNHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHNNHK...........",
                "...........KHNNHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHNNHK...........",
                "...........KHNNHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHNNHK...........",
                "...........KHNNHHHHHHHssHHHHsHHHHsHHHHsHHHHsHHHHHNNHK...........",
                "..........KNNNNHHHHHHHSsHHHsSHHHHSsHHHSsHHHSHHHHHNNNNK..........",
                "..........KNNNNNHHHHsHSSsHHSSsHHsSSHHsSSsHsSHHHHNNNNNK..........",
                ".........KNNNnNNNHHHSsSSSssSSSHHSSSssSSSSsSSHHHNNNnNNNK.........",
                ".........KNOnnnNNHHHSSSSSSSSSSsHSSSSSSSSSSSSHHHNNnnnONK.........",
                "........KNOOnnnNNHHHSSSSSSSSSSSsSSSSSSSSSSSSHHHNNnnnOONK........",
                "........KNOOnnnNNHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHNNnnnOONK........",
                "........KNOOnnnNNHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHNNnnnOONK........",
                ".........KNOnnnNNHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHNNnnnONK.........",
                ".........KNNnnNNNHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHNNNnnNNK.........",
                ".........KNNNNNNHHHHSSSSSSSSSSSSSSSSSSSSSSSSHHHHNNNNNNK.........",
                "..........KNNNNHHHHsSSSSSSSSSSSSSSSSSSSSSSSSsHHHHNNNNK..........",
                "..........KHHHHHHHHSSSSSSSSSSSSSSSSSSSSSSSSSSHHHHHHHHK..........",
                "..........KHHHHHHHHKSSSSSSSSSSSSSSSSSSSSSSSSKHHHHHHHHK..........",
                "..........KHHHHHHHHHKPPPPPSSSSSSSSSSSSPPPPPKHHHHHHHHHK..........",
                "..........KHHHHHHHHKKSPPPSSSSSSSSSSSSSSPPPSKKHHHHHHHHK..........",
                "..........KHHHHHHHHK.KSSSSSSSSSSSSSSSSSSSSK.KHHHHHHHHK..........",
                "..........KHHHHHHHHKKdKSSSSSSSSSSSSSSSSSSKdKKHHHHHHHHK..........",
                "..........KHHHHHHHHKKdKSSSSSSSSSSSSSSSSSKKdKKHHHHHHHHK..........",
                ".........KHHHHHHHHHKKddKKSSSSSSSSSSSSSSKKddKKHHHHHHHHHK.........",
                ".........KHHHHHHHHHKddddKKSSSSSSSSSSSSKKddddKHHHHHHHHHK.........",
                ".........KHHHHHHHHHKddddddKKSSSSSSSSKKddddddKHHHHHHHHHK.........",
                ".........KHHHHHHHHHKddddddddKKKKKKKKddddddddKHHHHHHHHHK.........",
                ".........KHHHHHHHHHKddddddddssssssssddddddddKHHHHHHHHHK.........",
                ".........KHHHHHHHHqqqqqqqqqqqqqqqqqqqqqqqqqqqqHHHHHHHHK.........",
                ".........KHHHHHHHqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqHHHHHHHK.........",
                ".........KHHHHHHHqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqHHHHHHHK.........",
                ".........KHHHHHHqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqHHHHHHK.........",
                ".........KHHHHHqqqqqqbbbbQQqqwqqqqwqqqqqqqqqqqqqqHHHHHK.........",
                ".........KHHHHHqbbbbbbbbbQQqqwqQQqwqqqqqqqqqqqqqqHHHHHK.........",
                ".........KHkbbbbbbbbbbbbbQQqqwQQQQwqqqqqqqqqqqqqqqHHHHK.........",
                ".........KHkbbbbbbbbbbbbbQQQQwQQQQwQQQqqqqqqqQQqqqqHHHK.........",
                "........KHHkkbbbbbbbbbbbbQQQQwQQQQwQQQQQqqqQQQQqqqqHHHHK........",
                "........KHHkkbbbbbbbbbbbbbSSQwQQQQwQQQQQQQQQQQQQqqqHHHHK........",
                "........KHHkkbbbbbbbbbbbbSSSSQQQQQQwQQQQQQQQQQQQqqqHHHHK........",
                "........KHHkkbbbbbbbbbbbbSSSSQQQQQQwQQQQQQQQQQQQqqqqHHHK........",
                "........KHHkkbbbbbFbFbbbbSSSSQQQQQQOQQQQQQQQQQQQqqqqHHHK........",
                "........KHHkkbbbbbFfFbbbSSSSOOQQQQOOQQQQQQQQQQQQqqqqHHHK........",
                "........KHHHkbbbbbfGGFbbSSSSQQQQQQQQQQQQQQQQQQQQQqqqHHHK........",
                "........KHHHkbbbbFfGfFbbbSSQQQQQQQQQQQQQQQQQQQQQQqqqqHHK........",
                "........KHHqkkbbbbFFFbbbbbbQQQQQQQQQQQQQQQQQQQQQQqqqqHHK........",
                "........KHHqkkbbbbbbbbbbbbbQQQQQQQQQQQQQQQQQQQQQQqqqqHHK........",
                "........KHHqkkbbbbbbbbbbbbbQQQQQQQQQQQQQQQQQQQQQQqqqqHHK........",
            ],
            eyes: [
                "open": Patch(x: 23, y: 27, rows: [".KKKK........KKKK.", "KKAAAK......KAAAKK", "AWWEAA......AWWEAA", "AWEEBA......AWEEBA", "BBEEBB......BBEEBB", ".BCCWB.......BCCWB", "..CC..........CC.."]),
                "sparkle": Patch(x: 23, y: 27, rows: [".KKKK........KKKK.", "KKWAAK......KAWAKK", "AWWWEA......AWWWEA", "AAWEEB......AAWEEB", "BBEEBB......BBEEBB", ".BCCWB.......BCCWB", "..CC..........CC.."]),
                "tired": Patch(x: 23, y: 29, rows: ["KKKKKK......KKKKKK", "AWEEBA......AWEEBA", "BBEEBB......BBEEBB", ".BCCWB.......BCCWB", "..CC..........CC.."]),
                "cry": Patch(x: 23, y: 28, rows: ["KK..............KK", "..KK..........KK..", "....KK......KK....", "..KK..........KK..", "KK..............KK"]),
                "closed": Patch(x: 23, y: 30, rows: ["K....K......K....K", ".KKKK........KKKK."]),
                "happy": Patch(x: 23, y: 29, rows: ["..KK..........KK..", ".K..K........K..K.", "K....K......K....K"]),
            ],
            mouths: [
                "small": Patch(x: 31, y: 38, rows: ["MM"]),
                "open": Patch(x: 30, y: 38, rows: ["MMMM", "MTTM", ".TT."]),
                "wavy": Patch(x: 30, y: 38, rows: ["MMMM"]),
                "o": Patch(x: 31, y: 38, rows: ["MM", "MM", "MM"]),
            ],
            extras: [
                "starBig": Patch(x: 3, y: 5, rows: ["..Y..", ".YYY.", "YYYYY", ".YYY.", "..Y.."]),
                "starSmall": Patch(x: 4, y: 6, rows: [".Y.", "YYY", ".Y."]),
                "sweatA": Patch(x: 8, y: 18, rows: [".X.", "XXX", "XXX", ".X."]),
                "sweatB": Patch(x: 8, y: 20, rows: [".X.", "XXX", "XXX", ".X."]),
                "tearsA": Patch(x: 25, y: 34, rows: ["X............X.", "XX...........XX", "XX...........XX"]),
                "tearsB": Patch(x: 25, y: 35, rows: ["X............X.", "XX...........XX", "XX...........XX"]),
                "zzzA": Patch(x: 3, y: 5, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "zzzB": Patch(x: 5, y: 2, rows: ["ZZZZ", "..Z.", ".Z..", "ZZZZ"]),
                "question": Patch(x: 3, y: 3, rows: [".ZZ.", "Z..Z", "...Z", "..Z.", ".Z..", "....", ".Z.."]),
            ]
        )
    )
}
